### ISSUE TITLE
Notifications are not shown sometimes (and sound not played, even if note shows)

### ISSUE THREAD

**Issue by angelo-fuchs** [deltachat/deltachat-android#1197]
Sometimes (I think always when I pause DC while on the contact list) my Notifications are not shown.

During debugging this I changed the sound that should be played when a new message arrives and since then it doesn't happen anymore, so if somebody can still reproduce this, please tell.

Most likely not related to #1033 as the problem here is within the handling of URIs during the playing, which could not cause the problems described there.

**Comment by angelo-fuchs** [comment]
Was able to reproduce it: This is the exception:

```
12-29 22:09:19.146  9470 29727 W System.err: java.lang.NullPointerException: Attempt to invoke virtual method 'android.net.Uri android.net.Uri.getCanonicalUri()' on a null object reference
12-29 22:09:19.147  9470 29727 W System.err: 	at android.media.Ringtone.play(Ringtone.java:333)
12-29 22:09:19.147  9470 29727 W System.err: 	at org.thoughtcrime.securesms.notifications.MessageNotifier.playNotificationSound(MessageNotifier.java:291)
12-29 22:09:19.147  9470 29727 W System.err: 	at org.thoughtcrime.securesms.notifications.MessageNotifier.notify(MessageNotifier.java:340)
12-29 22:09:19.147  9470 29727 W System.err: 	at org.thoughtcrime.securesms.notifications.MessageNotifier.sendSingleChatNotification(MessageNotifier.java:221)
12-29 22:09:19.147  9470 29727 W System.err: 	at org.thoughtcrime.securesms.notifications.MessageNotifier.sendNotifications(MessageNotifier.java:195)
12-29 22:09:19.147  9470 29727 W System.err: 	at org.thoughtcrime.securesms.notifications.MessageNotifier.updateNotification(MessageNotifier.java:105)
12-29 22:09:19.147  9470 29727 W System.err: 	at org.thoughtcrime.securesms.notifications.MessageNotifierCompat.lambda$updateNotification$0(MessageNotifierCompat.java:34)
12-29 22:09:19.147  9470 29727 W System.err: 	at org.thoughtcrime.securesms.notifications.-$$Lambda$MessageNotifierCompat$AwMZbMG_e2YI-_3Fb079nX9au-U.run(lambda)
12-29 22:09:19.147  9470 29727 W System.err: 	at org.thoughtcrime.securesms.util.Util.runOnAnyBackgroundThread(Util.java:328)
12-29 22:09:19.147  9470 29727 W System.err: 	at org.thoughtcrime.securesms.notifications.MessageNotifierCompat.updateNotification(MessageNotifierCompat.java:34)
12-29 22:09:19.148  9470 29727 W System.err: 	at org.thoughtcrime.securesms.ApplicationContext$2.handleEvent(ApplicationContext.java:140)
12-29 22:09:19.148  9470 29727 W System.err: 	at com.b44t.messenger.DcEventCenter.lambda$sendToObservers$1(DcEventCenter.java:77)
12-29 22:09:19.148  9470 29727 W System.err: 	at com.b44t.messenger.-$$Lambda$DcEventCenter$LOBBevoK2ZvITYKANy0AYd25Sp0.run(lambda)
12-29 22:09:19.148  9470 29727 W System.err: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
12-29 22:09:19.148  9470 29727 W System.err: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
12-29 22:09:19.148  9470 29727 W System.err: 	at java.lang.Thread.run(Thread.java:761)
```
