### ISSUE TITLE
A problem occurred starting process 'command 'cargo''

### ISSUE THREAD

**Issue by dicksonmulli** [deltachat/deltachat-android#1223]
I get this error when I try build the app. I have already installed rust. Kindly help.
- Logs: 
Caused by: java.io.IOException: Cannot run program "cargo" (in directory "$HOME/AndroidStudioProjects/deltachat-android/app/src/main/rust"): error=2, No such file or directory
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at net.rubygrapefruit.platform.internal.DefaultProcessLauncher.start(DefaultProcessLauncher.java:25)
	... 10 more
Caused by: java.io.IOException: error=2, No such file or directory
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 11 more

**Comment by r10s** [comment]
what did you do to get the build error? wondering where the deltachat-android/app/src/main/rust path comes from, it does not exist in the repo.

did you follow the steps described at https://github.com/deltachat/deltachat-android#build ?
in general, the rust build ist started by calling `./ndk-make.sh` in the repo's root directory. please also see the comments in the script about how to setup the needed toolchains
