### ISSUE TITLE
error on account switching

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-android#1327]
came over that when inspecting the logs from @webratte - so, we have to move some object from the DcContext to the AppContext.

```
2020-05-01 10:16:16.252 15434-15434/com.b44t.messenger.beta E/ActivityThread: Activity org.thoughtcrime.securesms.ConversationListActivity has leaked IntentReceiver org.thoughtcrime.securesms.connect.NetworkStateReceiver@b98ab57 that was originally registered here. Are you missing a call to unregisterReceiver()?
    android.app.IntentReceiverLeaked: Activity org.thoughtcrime.securesms.ConversationListActivity has leaked IntentReceiver org.thoughtcrime.securesms.connect.NetworkStateReceiver@b98ab57 that was originally registered here. Are you missing a call to unregisterReceiver()?
        at android.app.LoadedApk$ReceiverDispatcher.<init>(LoadedApk.java:1168)
        at android.app.LoadedApk.getReceiverDispatcher(LoadedApk.java:955)
        at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1302)
        at android.app.ContextImpl.registerReceiver(ContextImpl.java:1282)
        at android.app.ContextImpl.registerReceiver(ContextImpl.java:1276)
        at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:586)
        at org.thoughtcrime.securesms.connect.ApplicationDcContext.<init>(ApplicationDcContext.java:83)
        at org.thoughtcrime.securesms.connect.AccountManager.resetDcContext(AccountManager.java:103)
        at org.thoughtcrime.securesms.connect.AccountManager.switchAccount(AccountManager.java:150)
        at org.thoughtcrime.securesms.connect.AccountManager$SwitchAccountAsyncTask.doInBackground(AccountManager.java:241)
        at org.thoughtcrime.securesms.connect.AccountManager$SwitchAccountAsyncTask.doInBackground(AccountManager.java:223)
        at android.os.AsyncTask$2.call(AsyncTask.java:305)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:761)
```

**Comment by r10s** [comment]
closed by https://github.com/deltachat/deltachat-android/pull/1330
