### ISSUE TITLE
Share to multiple contacts

### ISSUE THREAD

**Issue by Hocuri** [deltachat/deltachat-android#1340]
- Expected behavior: When sharing to Delta Chat and then long-clicking an app, DC crashes.
- Actual behavior: It should be possible to share to multiple contacts.
- Logs:
```
   java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.Menu androidx.appcompat.view.ActionMode.getMenu()' on a null object reference
        at org.thoughtcrime.securesms.ConversationListFragment.onItemLongClick(ConversationListFragment.java:452)
        at org.thoughtcrime.securesms.ConversationListAdapter.lambda$onCreateViewHolder$2$ConversationListAdapter(ConversationListAdapter.java:122)
        at org.thoughtcrime.securesms.-$$Lambda$ConversationListAdapter$3T41Mf7zUsZE6210NC1tTC1ZMVI.onLongClick(Unknown Source:4)
        at android.view.View.performLongClickInternal(View.java:6677)
        at android.view.View.performLongClick(View.java:6635)
        at android.view.View.performLongClick(View.java:6653)
        at android.view.View$CheckForLongPress.run(View.java:25854)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6746)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

**Comment by Hocuri** [comment]
Not sure how easy this is to implement, might be that it's not worth it.
