### ISSUE TITLE
Profile Image selection doesn't work

### ISSUE THREAD

**Issue by cyBerta** [deltachat/deltachat-android#1469]
transferred from our forum (https://support.delta.chat/t/profil-picture-is-not-choosable-gallery-crashes/1030):
Delta Chat version

Delta Chat 1.8.1 (Android)

Expected behavior

That I can select a profile picture from my gallery or make a picture with my camera

Actual behavior

When I tab on the camera icon in the profile overview, the gallery shortly opens up and immediatly closes again.

Steps to reproduce the problem

    I open the app
    I go to “Settings”
    I go on the camera icon
    the screen for editing my profile opens up
    in this section I tab on the camera icon again
    the gallery opens and closes quick (it crashes)

Screen snapshots

not possible…

**Comment by cyBerta** [comment]
```

--------- beginning of crash
06-16 06:54:51.254 12726 12726 E AndroidRuntime: FATAL EXCEPTION: main
06-16 06:54:51.254 12726 12726 E AndroidRuntime: Process: chat.delta, PID: 12726
06-16 06:54:51.254 12726 12726 E AndroidRuntime: java.lang.IllegalArgumentException: Failed to find configured root that contains /storage/1D92-4986/Android/data/chat.delta/cache/capture8637733172079783987jpg
06-16 06:54:51.254 12726 12726 E AndroidRuntime: 	at androidx.core.content.FileProvider$SimplePathStrategy.getUriForFile(FileProvider.java:744)
06-16 06:54:51.254 12726 12726 E AndroidRuntime: 	at androidx.core.content.FileProvider.getUriForFile(FileProvider.java:418)
06-16 06:54:51.254 12726 12726 E AndroidRuntime: 	at org.thoughtcrime.securesms.util.FileProviderUtil.getUriFor(FileProviderUtil.java:19)
06-16 06:54:51.254 12726 12726 E AndroidRuntime: 	at org.thoughtcrime.securesms.CreateProfileActivity.createAvatarSelectionIntent(CreateProfileActivity.java:329)
06-16 06:54:51.254 12726 12726 E AndroidRuntime: 	at org.thoughtcrime.securesms.CreateProfileActivity.handleAvatarSelectionWithPermissions(CreateProfileActivity.java:360)
06-16 06:54:51.254 12726 12726 E AndroidRuntime: 	at org.thoughtcrime.securesms.CreateProfileActivity.lambda$6suxu8epwtdVptAk5CXri2yjlqk(Unknown Source:0)
06-16 06:54:51.254 12726 12726 E AndroidRuntime: 	at org.thoughtcrime.securesms.-$$Lambda$CreateProfileActivity$6suxu8epwtdVptAk5CXri2yjlqk.run(Unknown Source:2)
06-16 06:54:51.254 12726 12726 E AndroidRuntime: 	at org.thoughtcrime.securesms.permissions.PermissionsRequest.onResult(PermissionsRequest.java:85)
06-16 06:54:51.254 12726 12726 E AndroidRuntime: 	at org.thoughtcrime.securesms.permissions.Permissions$PermissionsBuilder.executePreGrantedPermissionsRequest(Permissions.java:153)
06-16 06:54:51.254 12726 12726 E AndroidRuntime: 	at org.thoughtcrime.securesms.permissions.Permissions$PermissionsBuilder.execute(Permissions.java:141)
06-16 06:54:51.254 12726 12726 E AndroidRuntime: 	at org.thoughtcrime.securesms.CreateProfileActivity.lambda$initializeResources$0$CreateProfileActivity(CreateProfileActivity.java:234)
06-16 06:54:51.254 12726 12726 E AndroidRuntime: 	at org.thoughtcrime.securesms.-$$Lambda$CreateProfileActivity$1BZFqVwryGxs1AazLyDwlO4jsr0.onClick(Unknown Source:2)
06-16 06:54:51.254 12726 12726 E AndroidRuntime: 	at android.view.View.performClick(View.java:7192)
06-16 06:54:51.254 12726 12726 E AndroidRuntime: 	at android.view.View.performClickInternal(View.java:7166)
06-16 06:54:51.254 12726 12726 E AndroidRuntime: 	at android.view.View.access$3500(View.java:824)
06-16 06:54:51.254 12726 12726 E AndroidRuntime: 	at android.view.View$PerformClick.run(View.java:27592)
06-16 06:54:51.254 12726 12726 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:888)
06-16 06:54:51.254 12726 12726 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:100)
06-16 06:54:51.254 12726 12726 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:213)
06-16 06:54:51.254 12726 12726 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8178)
06-16 06:54:51.254 12726 12726 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
06-16 06:54:51.254 12726 12726 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
06-16 06:54:51.254 12726 12726 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)
--------- beginning of system
06-16 22:02:57.514 31543 31543 D ActivityThread: Attach thread to application
06-16 22:02:57.764 31543 31543 V ActivityThread: callActivityOnCreate
06-16 22:02:57.888 31543 31543 D ActivityThread: add activity client record, r= ActivityRecord{9ca461b token=android.os.BinderProxy@1953355 {chat.delta/org.thoughtcrime.securesms.RoutingActivity}} token= android.os.BinderProxy@1953355
06-16 22:03:00.967 31543 31543 V ActivityThread: callActivityOnCreate
06-16 22:03:01.074 31543 31543 D ActivityThread: add activity client record, r= ActivityRecord{739f03 token=android.os.BinderProxy@8e489bc {chat.delta/org.thoughtcrime.securesms.ConversationActivity}} token= android.os.BinderProxy@8e489bc
06-16 22:03:01.576 31543 31543 D ActivityThread: Remove activity client record, r= ActivityRecord{9ca461b token=android.os.BinderProxy@1953355 {chat.delta/org.thoughtcrime.securesms.RoutingActivity}} token= android.os.BinderProxy@1953355
06-16 22:03:03.742 31543 31543 V ActivityThread: callActivityOnCreate
06-16 22:03:03.778 31543 31543 D ActivityThread: add activity client record, r= ActivityRecord{6ee9ae9 token=android.os.BinderProxy@8eb0bd1 {chat.delta/org.thoughtcrime.securesms.ConversationListActivity}} token= android.os.BinderProxy@8eb0bd1
06-16 22:03:04.065 31543 31543 D ActivityThread: Remove activity client record, r= ActivityRecord{739f03 token=android.os.BinderProxy@8e489bc {chat.delta/org.thoughtcrime.securesms.ConversationActivity}} token= android.os.BinderProxy@8e489bc
06-16 22:03:04.867 31543 31543 V ActivityThread: callActivityOnCreate
06-16 22:03:04.904 31543 31543 D ActivityThread: add activity client record, r= ActivityRecord{bcf3d9a token=android.os.BinderProxy@2afbc48 {chat.delta/org.thoughtcrime.securesms.qr.QrActivity}} token= android.os.BinderProxy@2afbc48
06-16 22:03:09.372 31543 31543 D ActivityThread: Remove activity client record, r= ActivityRecord{bcf3d9a token=android.os.BinderProxy@2afbc48 {chat.delta/org.thoughtcrime.securesms.qr.QrActivity}} token= android.os.BinderProxy@2afbc48
06-16 22:03:41.039 31543 31543 V ActivityThread: Handle window ActivityRecord{6ee9ae9 token=android.os.BinderProxy@8eb0bd1 {chat.delta/org.thoughtcrime.securesms.ConversationListActivity}} visibility: false
06-16 22:04:19.702 31543 31543 V ActivityThread: Handle window ActivityRecord{6ee9ae9 token=android.os.BinderProxy@8eb0bd1 {chat.delta/org.thoughtcrime.securesms.ConversationListActivity}} visibility: false
06-16 22:05:23.174 31543 31543 V ActivityThread: callActivityOnCreate
06-16 22:05:23.195 31543 31543 D ActivityThread: add activity client record, r= ActivityRecord{537d087 token=android.os.BinderProxy@e48e1f9 {chat.delta/org.thoughtcrime.securesms.ApplicationPreferencesActivity}} token= android.os.BinderProxy@e48e1f9
06-16 22:05:53.231 31543 31543 V ActivityThread: callActivityOnCreate
06-16 22:05:53.293 31543 31543 D ActivityThread: add activity client record, r= ActivityRecord{f15f265 token=android.os.BinderProxy@18b1a21 {chat.delta/org.thoughtcrime.securesms.CreateProfileActivity}} token= android.os.BinderProxy@18b1a21
06-16 22:05:54.274 31543 31543 E AndroidRuntime: FATAL EXCEPTION: main
06-16 22:05:54.274 31543 31543 E AndroidRuntime: Process: chat.delta, PID: 31543
06-16 22:05:54.274 31543 31543 E AndroidRuntime: java.lang.IllegalArgumentException: Failed to find configured root that contains /storage/1D92-4986/Android/data/chat.delta/cache/capture968772604353457195jpg
06-16 22:05:54.274 31543 31543 E AndroidRuntime: 	at androidx.core.content.FileProvider$SimplePathStrategy.getUriForFile(FileProvider.java:744)
06-16 22:05:54.274 31543 31543 E AndroidRuntime: 	at androidx.core.content.FileProvider.getUriForFile(FileProvider.java:418)
06-16 22:05:54.274 31543 31543 E AndroidRuntime: 	at org.thoughtcrime.securesms.util.FileProviderUtil.getUriFor(FileProviderUtil.java:19)
06-16 22:05:54.274 31543 31543 E AndroidRuntime: 	at org.thoughtcrime.securesms.CreateProfileActivity.createAvatarSelectionIntent(CreateProfileActivity.java:329)
06-16 22:05:54.274 31543 31543 E AndroidRuntime: 	at org.thoughtcrime.securesms.CreateProfileActivity.handleAvatarSelectionWithPermissions(CreateProfileActivity.java:360)
06-16 22:05:54.274 31543 31543 E AndroidRuntime: 	at org.thoughtcrime.securesms.CreateProfileActivity.lambda$6suxu8epwtdVptAk5CXri2yjlqk(Unknown Source:0)
06-16 22:05:54.274 31543 31543 E AndroidRuntime: 	at org.thoughtcrime.securesms.-$$Lambda$CreateProfileActivity$6suxu8epwtdVptAk5CXri2yjlqk.run(Unknown Source:2)
06-16 22:05:54.274 31543 31543 E AndroidRuntime: 	at org.thoughtcrime.securesms.permissions.PermissionsRequest.onResult(PermissionsRequest.java:85)
06-16 22:05:54.274 31543 31543 E AndroidRuntime: 	at org.thoughtcrime.securesms.permissions.Permissions$PermissionsBuilder.executePreGrantedPermissionsRequest(Permissions.java:153)
06-16 22:05:54.274 31543 31543 E AndroidRuntime: 	at org.thoughtcrime.securesms.permissions.Permissions$PermissionsBuilder.execute(Permissions.java:141)
06-16 22:05:54.274 31543 31543 E AndroidRuntime: 	at org.thoughtcrime.securesms.CreateProfileActivity.lambda$initializeResources$0$CreateProfileActivity(CreateProfileActivity.java:234)
06-16 22:05:54.274 31543 31543 E AndroidRuntime: 	at org.thoughtcrime.securesms.-$$Lambda$CreateProfileActivity$1BZFqVwryGxs1AazLyDwlO4jsr0.onClick(Unknown Source:2)
06-16 22:05:54.274 31543 31543 E AndroidRuntime: 	at android.view.View.performClick(View.java:7192)
06-16 22:05:54.274 31543 31543 E AndroidRuntime: 	at android.view.View.performClickInternal(View.java:7166)
06-16 22:05:54.274 31543 31543 E AndroidRuntime: 	at android.view.View.access$3500(View.java:824)
06-16 22:05:54.274 31543 31543 E AndroidRuntime: 	at android.view.View$PerformClick.run(View.java:27592)
06-16 22:05:54.274 31543 31543 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:888)
06-16 22:05:54.274 31543 31543 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:100)
06-16 22:05:54.274 31543 31543 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:213)
06-16 22:05:54.274 31543 31543 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8178)
06-16 22:05:54.274 31543 31543 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
06-16 22:05:54.274 31543 31543 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
06-16 22:05:54.274 31543 31543 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)
06-16 22:05:54.534   580   580 D ActivityThread: Attach thread to application
06-16 22:05:54.691   580   580 V ActivityThread: callActivityOnCreate
```

**Comment by cyBerta** [comment]
The filename `/storage/1D92-4986/Android/data/chat.delta/cache/capture8637733172079783987jpg` looks suspicious.
https://github.com/deltachat/deltachat-android/blob/8d0c0cb4c695b29417532fdceb4cfcaadb142a72/src/org/thoughtcrime/securesms/CreateProfileActivity.java#L375

should be `captureFile = File.createTempFile("capture", ".jpg", getExternalCacheDir());` instead of `captureFile = File.createTempFile("capture", "jpg", getExternalCacheDir());`
