### ISSUE TITLE
Crash on contacts permission problem

### ISSUE THREAD

**Issue by flub** [deltachat/deltachat-android#1639]
- Operating System (Linux/Mac/Windows/iOS/Android):Android device=OnePlus A0001 (bacon); android=10 lineage_bacon-userdebug 10 QQ3A. 200805.001 431caa5ea7; sdk=29
- Delta Chat Version: 1.12.5-gplay
- Expected behavior: Allows creating a new chat after pressing the new-chat button in the bottom right (+ in round circle)
- Actual behavior: hard crash of deltachat right after pressing the button.
- Steps to reproduce the problem: attempt to start new chat
- Screenshots: n/a
- Logs: adb logcat:
```
9-27 14:04:09.293  9760 10104 E DatabaseUtils: java.lang.SecurityException: Permission Denial: reading com.android.providers.contacts.ContactsProvider2 uri content://com.android.contacts/data/emails from pid=17987, uid=10155 requires android.permission.READ_CONTACTS, or grantUriPermission()
09-27 14:04:09.293  9760 10104 E DatabaseUtils: 	at android.content.ContentProvider.enforceReadPermissionInner(ContentProvider.java:729)
09-27 14:04:09.293  9760 10104 E DatabaseUtils: 	at android.content.ContentProvider$Transport.enforceReadPermission(ContentProvider.java:602)
09-27 14:04:09.293  9760 10104 E DatabaseUtils: 	at android.content.ContentProvider$Transport.query(ContentProvider.java:231)
09-27 14:04:09.293  9760 10104 E DatabaseUtils: 	at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:104)
09-27 14:04:09.293  9760 10104 E DatabaseUtils: 	at android.os.Binder.execTransactInternal(Binder.java:1021)
09-27 14:04:09.293  9760 10104 E DatabaseUtils: 	at android.os.Binder.execTransact(Binder.java:994)
09-27 14:04:09.297 17987 22137 E AndroidRuntime: FATAL EXCEPTION: Thread-7
09-27 14:04:09.297 17987 22137 E AndroidRuntime: Process: chat.delta, PID: 17987
09-27 14:04:09.297 17987 22137 E AndroidRuntime: java.lang.SecurityException: Permission Denial: reading com.android.providers.contacts.ContactsProvider2 uri content://com.android.contacts/data/emails from pid=17987, uid=10155 requires android.permission.READ_CONTACTS, or grantUriPermission()
09-27 14:04:09.297 17987 22137 E AndroidRuntime: 	at android.os.Parcel.createException(Parcel.java:2071)
09-27 14:04:09.297 17987 22137 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:2039)
09-27 14:04:09.297 17987 22137 E AndroidRuntime: 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:188)
09-27 14:04:09.297 17987 22137 E AndroidRuntime: 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:140)
09-27 14:04:09.297 17987 22137 E AndroidRuntime: 	at android.content.ContentProviderProxy.query(ContentProviderNative.java:423)
09-27 14:04:09.297 17987 22137 E AndroidRuntime: 	at android.content.ContentResolver.query(ContentResolver.java:944)
09-27 14:04:09.297 17987 22137 E AndroidRuntime: 	at android.content.ContentResolver.query(ContentResolver.java:880)
09-27 14:04:09.297 17987 22137 E AndroidRuntime: 	at android.content.ContentResolver.query(ContentResolver.java:836)
09-27 14:04:09.297 17987 22137 E AndroidRuntime: 	at org.thoughtcrime.securesms.contacts.ContactAccessor.getAllSystemContacts(ContactAccessor.java:59)
09-27 14:04:09.297 17987 22137 E AndroidRuntime: 	at org.thoughtcrime.securesms.contacts.ContactAccessor.getAllSystemContactsAsString(ContactAccessor.java:63)
09-27 14:04:09.297 17987 22137 E AndroidRuntime: 	at org.thoughtcrime.securesms.ContactSelectionListFragment$3.run(ContactSelectionListFragment.java:345)
```

It seems like the app is denied contacts permissions from that exception.  Which I can confirm, going to device settings and looking up the app permissions it has the contacts listed as `Denied/Never accessed`.  I'm not sure if I ever denied contact access or not.  But two things would be nice:
- work just fine without having access to the contacts
- prompt me again for access, or if you know i already denied once, have a button in contact list to allow me to ask for access to device contacts again.

Most interestingly, I can not fix this by changing the "App permissions" from the device settings.  Setting contacts to "Allow" there just flips it back to "Deny".  logcat does not show anything useful when doing this:

```
09-27 14:18:56.791 24239 24239 V AppPermissionFragment: Permission changed via UI with sessionId=-4264631084073555980 changeId=7750505736004164153 uid=10155 packageName=chat.delta permission=android.permission.READ_CONTACTS isGranted=true
09-27 14:18:56.808 24239 24239 W AppPermissionFragment: Permissions changed.
```

It is likely this last part is an OS bug for my device I guess?

**Comment by Hocuri** [comment]
Strange... Are other apps able to access the contacts?

Anyway let's just catch the exception, seems to be a very rare bug.
