### ISSUE TITLE
app freeze/crash when "Show all locations" menu option is selected

### ISSUE THREAD

**Issue by adbenitez** [deltachat/deltachat-android#1936]
- Android version: 10
- Delta Chat version: 1.20.2
- Logs:

```
05-22 14:43:39.061 15485 15485 E Mbgl-LocationComponent: Failed to obtain last location update
05-22 14:43:39.061 15485 15485 E Mbgl-LocationComponent: java.lang.Exception: Last location unavailable
05-22 14:43:39.061 15485 15485 E Mbgl-LocationComponent:        at com.mapbox.android.core.location.MapboxFusedLocationEngineImpl.getLastLocation(MapboxFusedLocationEngineImpl.java:41)
05-22 14:43:39.061 15485 15485 E Mbgl-LocationComponent:        at com.mapbox.android.core.location.LocationEngineProxy.getLastLocation(LocationEngineProxy.java:25)
05-22 14:43:39.061 15485 15485 E Mbgl-LocationComponent:        at com.mapbox.mapboxsdk.location.LocationComponent.setLastLocation(LocationComponent.java:1480)
05-22 14:43:39.061 15485 15485 E Mbgl-LocationComponent:        at com.mapbox.mapboxsdk.location.LocationComponent.onLocationLayerStart(LocationComponent.java:1271)
05-22 14:43:39.061 15485 15485 E Mbgl-LocationComponent:        at com.mapbox.mapboxsdk.location.LocationComponent.enableLocationComponent(LocationComponent.java:1387)
05-22 14:43:39.061 15485 15485 E Mbgl-LocationComponent:        at com.mapbox.mapboxsdk.location.LocationComponent.setLocationComponentEnabled(LocationComponent.java:516)
05-22 14:43:39.061 15485 15485 E Mbgl-LocationComponent:        at org.thoughtcrime.securesms.map.MapDataManager.initLocationComponent(MapDataManager.java:454)
05-22 14:43:39.061 15485 15485 E Mbgl-LocationComponent:        at org.thoughtcrime.securesms.map.MapDataManager.<init>(MapDataManager.java:154)
05-22 14:43:39.061 15485 15485 E Mbgl-LocationComponent:        at org.thoughtcrime.securesms.map.MapActivity.lambda$onCreate$3$MapActivity(MapActivity.java:154)
05-22 14:43:39.061 15485 15485 E Mbgl-LocationComponent:        at org.thoughtcrime.securesms.map.-$$Lambda$MapActivity$yfClTjHimGbutrP8I8dMXeXxNMg.onStyleLoaded(Unknown Source:4)
05-22 14:43:39.061 15485 15485 E Mbgl-LocationComponent:        at com.mapbox.mapboxsdk.maps.MapboxMap.notifyStyleLoaded(MapboxMap.java:959)
05-22 14:43:39.061 15485 15485 E Mbgl-LocationComponent:        at com.mapbox.mapboxsdk.maps.MapboxMap.onFinishLoadingStyle(MapboxMap.java:221)
05-22 14:43:39.061 15485 15485 E Mbgl-LocationComponent:        at com.mapbox.mapboxsdk.maps.MapView$MapCallback.onDidFinishLoadingStyle(MapView.java:1328)
05-22 14:43:39.061 15485 15485 E Mbgl-LocationComponent:        at com.mapbox.mapboxsdk.maps.MapChangeReceiver.onDidFinishLoadingStyle(MapChangeReceiver.java:198)
05-22 14:43:39.061 15485 15485 E Mbgl-LocationComponent:        at com.mapbox.mapboxsdk.maps.NativeMapView.onDidFinishLoadingStyle(NativeMapView.java:1106)
05-22 14:43:39.061 15485 15485 E Mbgl-LocationComponent:        at android.os.MessageQueue.nativePollOnce(Native Method)
05-22 14:43:39.061 15485 15485 E Mbgl-LocationComponent:        at android.os.MessageQueue.next(MessageQueue.java:336)
05-22 14:43:39.061 15485 15485 E Mbgl-LocationComponent:        at android.os.Looper.loop(Looper.java:197)
05-22 14:43:39.061 15485 15485 E Mbgl-LocationComponent:        at android.app.ActivityThread.main(ActivityThread.java:7948)
05-22 14:43:39.061 15485 15485 E Mbgl-LocationComponent:        at java.lang.reflect.Method.invoke(Native Method)
05-22 14:43:39.061 15485 15485 E Mbgl-LocationComponent:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
05-22 14:43:39.061 15485 15485 E Mbgl-LocationComponent:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1075)
```

**Comment by adbenitez** [comment]
> `05-22 14:43:39.061 15485 15485 E Mbgl-LocationComponent: java.lang.Exception: Last location unavailable`

actually this error is logged but there is no crash/throwing that could be catch on our side, it is captured in the mapbox lib, and then there is an ANR, but I just realized that it seems to happen only if you are always offline, just being online once then seems mapbox fetches something and this ANR never happens again, even if you are offline, anyway seems something that is not a bug on our side, and to get an actual crash is a pretty rare case like a network where you have access only to your email server, and that you have never used the maps while actually online.

related issue: https://github.com/mapbox/mapbox-events-android/issues/374
