### ISSUE TITLE
Permission denied (os error 13)

### ISSUE THREAD

**Issue by Gh0stz0x** [deltachat/deltachat-android#2120]
- Android version: Android 10
- Device: Huawei Mate 20
- Delta Chat version: 1.24.0
- Expected behavior: When I make a back-up it does it without problems.
- Actual behavior: When I make a back-up it blocks me after it has reached 1% and a popup appears saying that "Could not create xxxxx Permission denied (os error 13)"
- Steps to reproduce the problem: Make a backup - Screenshots: 
![Screenshot_20211106_145746](https://user-images.githubusercontent.com/74795149/140614282-d72da629-985d-4f96-8e83-cd23a1e9c884.jpg)
- Logs: 
**This log may contain sensitive information. If you want to post it publicly you may examine and edit it beforehand.**

device=HUAWEI HMA-L29 (HMA-L29)
android=10 (10.1.0.288C55, HMA-L29 10.1.0.288(C55E8R1P5))
sdk=29
memory=19M (37.02% free, 512M max)
memoryClass=384
host=cn-central-1b-fd54bc7601596224378655-1430093079-64fqw
applicationId=chat.delta.beta
app=Delta Chat 1.24.0-gplay-debug
installer=com.google.android.packageinstaller
ignoreBatteryOptimizations=true
notifications=true
reliableService=true
lang=it_IT
rtl=false

arch=64
bcc_self=0
blobdir=/data/user/0/chat.delta.beta/files/accounts/1fb337149e0143e6848d4bb087b5a339/dc.db-blobs
bot=0
configured_mvbox_folder=DeltaChat
configured_sentbox_folder=<unset>
database_dir=/data/user/0/chat.delta.beta/files/accounts/1fb337149e0143e6848d4bb087b5a339/dc.db
database_version=80
delete_device_after=0
delete_server_after=1
deltachat_core_version=v1.62.0
display_name=Gh0stz0x
download_limit=655360
e2ee_enabled=1
entered_account_settings=andrea@testrun.org imap:unset:***:unset:0:cert_automatic smtp:unset:0:unset:0:cert_automatic 0
fetch_existing_msgs=1
fingerprint=3AD394D46300EB85B871128A035C728FAB798940
folders_configured=3
inbox_watch=1
is_configured=1
journal_mode=wal
key_gen_type=0
last_housekeeping=1636210948
level=awesome
mdns_enabled=1
media_quality=0
messages_in_contact_requests=4
mvbox_move=0
mvbox_watch=1
num_cpus=8
number_of_chat_messages=16
number_of_chats=12
number_of_contacts=410
private_key_count=1
public_key_count=14
quota_exceeding=0
scan_all_folders_debounce_secs=60
selfavatar=/data/user/0/chat.delta.beta/files/accounts/1fb337149e0143e6848d4bb087b5a339/dc.db-blobs/selfavatar204307302038657123.jpg
send_sync_msgs=0
sentbox_move=0
sentbox_watch=1
show_emails=2
socks5_enabled=0
sqlite_version=3.35.4
uptime=1h 35m 16s
used_account_settings=andrea@testrun.org imap:andrea@testrun.org:***:testrun.org:993:cert_strict smtp:andrea@testrun.org:***:testrun.org:587:cert_strict AUTH_NORMAL 0x4
webrtc_instance=https://meet.jit.si/$ROOM

--------- beginning of system
11-06 15:54:08.628 21060 21060 I ViewRootImpl: dispatchDetachedFromWindow in doDie
11-06 15:54:15.062 21060 21060 I ViewRootImpl: dispatchDetachedFromWindow in doDie
11-06 15:54:15.122 21060 21060 I ViewRootImpl: dispatchDetachedFromWindow in doDie
11-06 15:54:16.382 21060 21060 I ViewRootImpl: dispatchDetachedFromWindow in doDie
11-06 15:54:44.783 21060 21060 I ViewRootImpl: dispatchDetachedFromWindow in doDie
11-06 15:54:48.065 21060 21060 I ViewRootImpl: dispatchDetachedFromWindow in doDie
11-06 15:55:03.586 21060 21060 I ViewRootImpl: dispatchDetachedFromWindow in doDie
11-06 15:55:04.649 21060 21060 I ViewRootImpl: dispatchDetachedFromWindow in doDie
11-06 15:55:06.687 21060 21060 I ViewRootImpl: dispatchDetachedFromWindow in doDie
11-06 15:55:07.754 21060 21060 I ViewRootImpl: dispatchDetachedFromWindow in doDie
11-06 15:57:37.925 21060 21060 I ViewRootImpl: dispatchDetachedFromWindow in doDie
11-06 15:57:43.735 21060 21060 I ViewRootImpl: dispatchDetachedFromWindow in doDie
11-06 15:57:43.780 21060 21060 I ViewRootImpl: dispatchDetachedFromWindow in doDie
11-06 15:57:44.964 21060 21060 I ViewRootImpl: dispatchDetachedFromWindow in doDie
11-06 15:58:19.165 21060 21060 I ViewRootImpl: dispatchDetachedFromWindow in doDie
11-06 15:58:19.204 21060 21060 I ViewRootImpl: dispatchDetachedFromWindow in doDie
11-06 15:59:49.475 21060 21060 I ViewRootImpl: dispatchDetachedFromWindow in doDie
11-06 15:59:49.509 21060 21060 I ViewRootImpl: dispatchDetachedFromWindow in doDie
11-06 15:59:52.179 21060 21060 I ViewRootImpl: dispatchDetachedFromWindow in doDie
11-06 16:02:19.132 21060 21060 I ViewRootImpl: dispatchDetachedFromWindow in doDie
11-06 16:02:21.122 21060 21060 I ViewRootImpl: dispatchDetachedFromWindow in doDie
11-06 16:02:28.572 21060 21060 I ViewRootImpl: dispatchDetachedFromWindow in doDie
11-06 16:02:28.634 21060 21060 I ViewRootImpl: dispatchDetachedFromWindow in doDie
--------- beginning of main
11-06 16:03:51.689 21060 21060 I DeltaChat: ++++++++++++++++++ first ForegroundDetector.onActivityStarted() ++++++++++++++++++
11-06 16:03:51.689 21060 21105 I DeltaChat: src/context.rs:168: starting IO
11-06 16:03:51.689 21060 21105 I DeltaChat: src/context.rs:170: IO is already running
11-06 16:03:51.691 21060  8338 I DeltaChat: calling maybeNetwork()
11-06 16:03:51.691 21060  8338 I DeltaChat: maybeNetwork() returned
11-06 16:03:51.692 21060 21060 I PassphraseRequiredActionBarActivity: onResume()
11-06 16:03:51.694 21060 21105 I DeltaChat: src/scheduler.rs:315: smtp fake idle - interrupted
11-06 16:03:51.694 21060 21105 I DeltaChat: src/job.rs:1294: loading job for Smtp-thread
11-06 16:03:51.694 21060 21105 I DeltaChat: src/imap/idle.rs:83: Idle wait was interrupted
11-06 16:03:51.694 21060 21105 I DeltaChat: src/imap/idle.rs:83: Idle wait was interrupted
11-06 16:03:51.694 21060 21105 I DeltaChat: src/scheduler.rs:220: Can not watch configured_sentbox_folder folder, not set
11-06 16:03:51.694 21060 21105 I DeltaChat: src/scheduler.rs:308: smtp fake idle - started
11-06 16:03:51.694 21060 21105 I DeltaChat: src/imap/idle.rs:117: IMAP-fake-IDLE: no folder, waiting for interrupt
11-06 16:03:51.733 21060 21060 I HwViewRootImpl: removeInvalidNode all the node in jank list is out of time
11-06 16:03:51.874 21060 21105 I DeltaChat: src/job.rs:1294: loading job for Imap-thread
11-06 16:03:52.115 21060 21105 I DeltaChat: src/imap.rs:766: 0 mails read from "DeltaChat".
11-06 16:03:52.117 21060 21105 I DeltaChat: src/imap.rs:766: 0 mails read from "INBOX".
11-06 16:03:52.275 21060 21105 I DeltaChat: src/imap/idle.rs:57: DeltaChat: Idle entering wait-on-remote state
11-06 16:03:52.295 21060 21105 I DeltaChat: src/imap/idle.rs:57: INBOX: Idle entering wait-on-remote state
11-06 16:03:52.690 21060 21060 I PassphraseRequiredActionBarActivity: onPause()
11-06 16:03:52.951 21060 21118 W libEGL  : EGLNativeWindowType 0x72b0f02850 disconnect failed
11-06 16:03:52.956 21060 21118 W libEGL  : EGLNativeWindowType 0x7262c3d550 disconnect failed
11-06 16:03:52.960 21060 21060 I DeltaChat: ++++++++++++++++++ last ForegroundDetector.onActivityStopped() ++++++++++++++++++
11-06 16:03:53.708 21060 21060 I PassphraseRequiredActionBarActivity: onDestroy()
11-06 16:03:53.710 21060 21060 I ViewRootImpl: dispatchDetachedFromWindow in doDie
11-06 16:03:53.725 21060 21060 I PassphraseRequiredActionBarActivity: onDestroy()
11-06 16:03:53.726 21060 21060 I ViewRootImpl: dispatchDetachedFromWindow in doDie
11-06 16:03:53.730 21060 21060 E WindowManager: 
11-06 16:03:53.730 21060 21060 E WindowManager: android.view.WindowLeaked: Activity org.thoughtcrime.securesms.ApplicationPreferencesActivity has leaked window DecorView@d60418a[ApplicationPreferencesActivity] that was originally added here
11-06 16:03:53.730 21060 21060 E WindowManager: 	at android.view.ViewRootImpl.<init>(ViewRootImpl.java:716)
11-06 16:03:53.730 21060 21060 E WindowManager: 	at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:450)
11-06 16:03:53.730 21060 21060 E WindowManager: 	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:121)
11-06 16:03:53.730 21060 21060 E WindowManager: 	at android.app.Dialog.show(Dialog.java:510)
11-06 16:03:53.730 21060 21060 E WindowManager: 	at androidx.appcompat.app.AlertDialog$Builder.show(AlertDialog.java:1009)
11-06 16:03:53.730 21060 21060 E WindowManager: 	at org.thoughtcrime.securesms.preferences.ListSummaryPreferenceFragment.handleEvent(ListSummaryPreferenceFragment.java:143)
11-06 16:03:53.730 21060 21060 E WindowManager: 	at org.thoughtcrime.securesms.connect.DcEventCenter.lambda$sendToObservers$0(DcEventCenter.java:76)
11-06 16:03:53.730 21060 21060 E WindowManager: 	at org.thoughtcrime.securesms.connect.DcEventCenter$$ExternalSyntheticLambda0.run(Unknown Source:4)
11-06 16:03:53.730 21060 21060 E WindowManager: 	at android.os.Handler.handleCallback(Handler.java:900)
11-06 16:03:53.730 21060 21060 E WindowManager: 	at android.os.Handler.dispatchMessage(Handler.java:103)
11-06 16:03:53.730 21060 21060 E WindowManager: 	at android.os.Looper.loop(Looper.java:219)
11-06 16:03:53.730 21060 21060 E WindowManager: 	at android.app.ActivityThread.main(ActivityThread.java:8387)
11-06 16:03:53.730 21060 21060 E WindowManager: 	at java.lang.reflect.Method.invoke(Native Method)
11-06 16:03:53.730 21060 21060 E WindowManager: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
11-06 16:03:53.730 21060 21060 E WindowManager: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1055)
11-06 16:03:53.730 21060 21060 I ViewRootImpl: dispatchDetachedFromWindow in doDie
11-06 16:05:55.501 21060 21105 I DeltaChat: src/imap/idle.rs:73: Idle has NewData ResponseData { raw: 4096, response: MailboxData(Exists(533)) }
11-06 16:05:55.651 21060 21105 I DeltaChat: src/job.rs:1294: loading job for Imap-thread
11-06 16:05:55.977 21060 21105 I DeltaChat: src/dc_receive_imf.rs:83: Receiving message INBOX/96699, seen=false...
11-06 16:05:55.982 21060 21105 I DeltaChat: src/dc_receive_imf.rs:113: received message 96699 has Message-Id: Mr.bI6ENV9DGJZ.zFwhCPBxeAa@riseup.net
11-06 16:05:55.983 21060 21105 I DeltaChat: src/dc_receive_imf.rs:1424: creating ad-hoc group prevented from caller
11-06 16:05:56.033 21060 21105 I DeltaChat: src/dc_receive_imf.rs:1173: Message has 1 parts and is assigned to chat #Chat#Trash.
11-06 16:05:56.033 21060 21105 I DeltaChat: src/job.rs:206: saving job for Imap-thread: Job { job_id: 0, action: DeleteMsgOnImap, foreign_id: 178, desired_timestamp: 1636211156, added_timestamp: 1636211156, tries: 0, param: Params { inner: {} } }
11-06 16:05:56.047 21060 21105 I DeltaChat: src/job.rs:1252: interrupt: imap
11-06 16:05:56.047 21060 21105 I DeltaChat: src/message.rs:1501: handle_mdn found no message with Message-ID "Gr.MkHMTOtfNRM.5pBTMOnMAMs@testrun.org" sent by us in the database
11-06 16:05:56.051 21060 21105 I DeltaChat: src/imap.rs:766: 1 mails read from "INBOX".
11-06 16:05:56.211 21060 21105 I DeltaChat: src/imap.rs:766: 0 mails read from "INBOX".
11-06 16:05:56.211 21060 21105 I DeltaChat: src/imap/scan_folders.rs:26: Starting full folder scan
11-06 16:05:56.383 21060 21105 I DeltaChat: src/imap.rs:1448: ignoring unsolicited response Recent(1)
11-06 16:05:56.385 21060 21105 I DeltaChat: src/imap/idle.rs:40: skip idle, got interrupt InterruptInfo { probe_network: false, msg_id: None }
11-06 16:05:56.385 21060 21105 I DeltaChat: src/job.rs:1294: loading job for Imap-thread
11-06 16:05:56.385 21060 21105 I DeltaChat: src/job.rs:1083: Inbox-job #111, action DeleteMsgOnImap started...
11-06 16:05:56.385 21060 21105 I DeltaChat: src/job.rs:1152: Inbox begin immediate try 0 of job #111, action DeleteMsgOnImap
11-06 16:05:56.387 21060 21105 I DeltaChat: src/job.rs:630: Running delete job for message Mr.bI6ENV9DGJZ.zFwhCPBxeAa@riseup.net which has 1 entries in the database
11-06 16:05:56.732 21060 21105 I DeltaChat: src/job.rs:1181: Finished immediate try 0 of job #111, action DeleteMsgOnImap
11-06 16:05:56.732 21060 21105 I DeltaChat: src/job.rs:1133: Inbox removes job #111, action DeleteMsgOnImap as it succeeded
11-06 16:05:56.733 21060 21105 I DeltaChat: src/job.rs:1294: loading job for Imap-thread
11-06 16:05:56.734 21060 21105 I DeltaChat: src/imap/select_folder.rs:35: Expunge messages in "INBOX".
11-06 16:05:56.904 21060 21105 I DeltaChat: src/imap/select_folder.rs:40: close/expunge succeeded
11-06 16:05:57.055 21060 21105 I DeltaChat: src/imap.rs:661: No new emails in folder INBOX
11-06 16:05:57.213 21060 21105 I DeltaChat: src/imap/idle.rs:57: INBOX: Idle entering wait-on-remote state
11-06 16:06:00.569 21060 21060 W ActivityThread: handleWindowVisibility: no activity for token android.os.BinderProxy@8cf33a1
11-06 16:06:00.582 21060 21060 W PassphraseRequiredActionBarActivity: onCreate(null)
11-06 16:06:00.593 21060 21105 I DeltaChat: src/chat.rs:2957: device-message update_1_24n_android already added
11-06 16:06:00.597 21060 21060 I DecorView[]:  old windowMode:0 new windoMode:1
11-06 16:06:00.624 21060 21060 I DeltaChat: ++++++++++++++++++ first ForegroundDetector.onActivityStarted() ++++++++++++++++++
11-06 16:06:00.624 21060 21105 I DeltaChat: src/context.rs:168: starting IO
11-06 16:06:00.624 21060 21105 I DeltaChat: src/context.rs:170: IO is already running
11-06 16:06:00.625 21060  8705 I DeltaChat: calling maybeNetwork()
11-06 16:06:00.625 21060  8705 I DeltaChat: maybeNetwork() returned
11-06 16:06:00.625 21060 21105 I DeltaChat: src/imap/idle.rs:83: Idle wait was interrupted
11-06 16:06:00.626 21060 21105 I DeltaChat: src/scheduler.rs:315: smtp fake idle - interrupted
11-06 16:06:00.626 21060 21105 I DeltaChat: src/job.rs:1294: loading job for Smtp-thread
11-06 16:06:00.626 21060 21105 I DeltaChat: src/imap/idle.rs:83: Idle wait was interrupted
11-06 16:06:00.626 21060 21105 I DeltaChat: src/scheduler.rs:220: Can not watch configured_sentbox_folder folder, not set
11-06 16:06:00.626 21060 21105 I DeltaChat: src/imap/idle.rs:117: IMAP-fake-IDLE: no folder, waiting for interrupt
11-06 16:06:00.626 21060 21105 I DeltaChat: src/scheduler.rs:308: smtp fake idle - started
11-06 16:06:00.633 21060 31444 I ConversationListFragment: executing debounced chatlist loading
11-06 16:06:00.636 21060 21060 I PassphraseRequiredActionBarActivity: onResume()
11-06 16:06:00.694 21060 21060 I HwViewRootImpl: removeInvalidNode all the node in jank list is out of time
11-06 16:06:00.696 21060 21060 W InputMethodManager: startInputReason = 1
11-06 16:06:00.784 21060 21105 I DeltaChat: src/job.rs:1294: loading job for Imap-thread
11-06 16:06:00.952 21060 21105 I DeltaChat: src/imap.rs:766: 0 mails read from "INBOX".
11-06 16:06:01.040 21060 21105 I DeltaChat: src/imap.rs:766: 0 mails read from "DeltaChat".
11-06 16:06:01.143 21060 21105 I DeltaChat: src/imap/idle.rs:57: INBOX: Idle entering wait-on-remote state
11-06 16:06:01.161 21060 31444 I DirectShareUtil: Updated dynamic shortcuts, success: true
11-06 16:06:01.202 21060 21105 I DeltaChat: src/imap/idle.rs:57: DeltaChat: Idle entering wait-on-remote state
11-06 16:06:01.404 21060 21060 W Settings: Setting device_provisioned has moved from android.provider.Settings.Secure to android.provider.Settings.Global.
11-06 16:06:02.188 21060 21060 I PassphraseRequiredActionBarActivity: onPause()
11-06 16:06:02.199 21060 21060 W ActivityThread: handleWindowVisibility: no activity for token android.os.BinderProxy@48dd63c
11-06 16:06:02.202 21060 21060 W PassphraseRequiredActionBarActivity: onCreate(null)
11-06 16:06:02.206 21060 21060 I DecorView[]:  old windowMode:0 new windoMode:1
11-06 16:06:02.218 21060 21060 I PassphraseRequiredActionBarActivity: onResume()
11-06 16:06:02.270 21060 21060 W InputMethodManager: startInputReason = 1
11-06 16:06:02.344 21060 21060 I ViewRootImpl: dispatchDetachedFromWindow in doDie
11-06 16:06:02.348 21060 21118 W libEGL  : EGLNativeWindowType 0x731164d750 disconnect failed
11-06 16:06:02.462 21060 21118 W libEGL  : EGLNativeWindowType 0x7262c3d550 disconnect failed
11-06 16:06:03.002 21060 21060 W Settings: Setting device_provisioned has moved from android.provider.Settings.Secure to android.provider.Settings.Global.
11-06 16:06:03.541 21060 21060 I InputTransport: Fun_filterMotionEvent reportMoveEvent!
11-06 16:06:03.564 21060 21060 W HiTouch_PressGestureDetector: Touch pointer move a lot. The moving distance of X is:27.555878, limit is:60The moving distance of Y is:154.65796, limit is:60
11-06 16:06:04.238 21060 21060 I PassphraseRequiredActionBarActivity: onPause()
11-06 16:06:05.584 21060 21060 I PassphraseRequiredActionBarActivity: onResume()
11-06 16:06:05.779 21060 21060 W InputMethodManager: startInputReason = 1
11-06 16:06:09.365 21060 21060 W HiTouch_PressGestureDetector: Touch pointer move a lot. The moving distance of X is:8.831833, limit is:60The moving distance of Y is:79.98193, limit is:60
11-06 16:06:09.397 21060 21060 I HwViewGroupImpl: accelerateSliding accelerate sliding.. mTriggeredMoveCount = 2
11-06 16:06:10.213 21060 21060 I PassphraseRequiredActionBarActivity: onPause()
11-06 16:06:10.223 21060 21060 W ActivityThread: handleWindowVisibility: no activity for token android.os.BinderProxy@6999b81
11-06 16:06:10.232 21060 21060 I DecorView[]:  old windowMode:0 new windoMode:1

**Comment by Gh0stz0x** [comment]
Excuse me, but unfortunately it doesn't even let me save the log.
Delta Chat has all permissions enabled, so I don't know what that could be. 🤔

**Comment by r10s** [comment]
i could reproduce that issue with android10 in the emulator.

i also tried android6, android7 and android11 - all of them work as expected.
