### ISSUE TITLE
app crashes exporting several attachments at the same time

### ISSUE THREAD

**Issue by adbenitez** [deltachat/deltachat-android#2124]
this issue is likely related to the new `api-30` changes
 
- Android version: 11
- Delta Chat version: 1.24.2
- Steps to reproduce the problem: select more than one attachment and press "export attachments"
- Logs:
```
11-07 14:17:16.854 27811 27811 E AndroidRuntime: java.lang.NullPointerException: uri                                                                                   
11-07 14:17:16.854 27811 27811 E AndroidRuntime:        at java.util.Objects.requireNonNull(Objects.java:245)                                                          
11-07 14:17:16.854 27811 27811 E AndroidRuntime:        at android.content.ContentResolver.query(ContentResolver.java:1167)                                            
11-07 14:17:16.854 27811 27811 E AndroidRuntime:        at android.content.ContentResolver.query(ContentResolver.java:1125)                                            
11-07 14:17:16.854 27811 27811 E AndroidRuntime:        at androidx.core.content.ContentResolverCompat.query(ContentResolverCompat.java:81)                            
11-07 14:17:16.854 27811 27811 E AndroidRuntime:        at androidx.loader.content.CursorLoader.loadInBackground(CursorLoader.java:63)                                 
11-07 14:17:16.854 27811 27811 E AndroidRuntime:        at org.thoughtcrime.securesms.util.SaveAttachmentTask.getRealPathFromURI(SaveAttachmentTask.java:138)          
11-07 14:17:16.854 27811 27811 E AndroidRuntime:        at org.thoughtcrime.securesms.util.SaveAttachmentTask.onPostExecute(SaveAttachmentTask.java:323)               
11-07 14:17:16.854 27811 27811 E AndroidRuntime:        at org.thoughtcrime.securesms.util.SaveAttachmentTask.onPostExecute(SaveAttachmentTask.java:38)                
11-07 14:17:16.854 27811 27811 E AndroidRuntime:        at android.os.AsyncTask.finish(AsyncTask.java:771)                                                             
11-07 14:17:16.854 27811 27811 E AndroidRuntime:        at android.os.AsyncTask.access$900(AsyncTask.java:199)                                                         
11-07 14:17:16.854 27811 27811 E AndroidRuntime:        at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:788)                                      
11-07 14:17:16.854 27811 27811 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:106)
11-07 14:17:16.854 27811 27811 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:246)
11-07 14:17:16.854 27811 27811 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:8587)
11-07 14:17:16.854 27811 27811 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
11-07 14:17:16.854 27811 27811 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
11-07 14:17:16.854 27811 27811 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
```

**Comment by adbenitez** [comment]
the bug was introduced in:

https://github.com/deltachat/deltachat-android/pull/2087/files#diff-e1afa18bd149b8fc8093a3322665586fc77ee93311e36e86b329e89f41ccbb65R320

I will push a fix
