### ISSUE TITLE
When opening the map, DeltaChat crashes

### ISSUE THREAD

**Issue by icke68746** [deltachat/deltachat-android#2140]
- Android version:11
- Device:Samsung Galaxy S10+
- Delta Chat version:1.24.4-gplay-debug (841c1d7f-gplay-debug-1.24.4.apk)
- Expected behavior: When you click on Open map, the map opens.
- Actual behavior: When opening the map, DeltaChat crashes.
- (In version 841c1d7f-gplay-debug-1.24.2.apk, opening the map did not work either. In version deltachat-gplay-debug-1.23.0.apk the map could be opened.)
- Steps to reproduce the problem: Click on the map symbol.
[2021.11.21-DC_Mausi.log.txt](https://github.com/deltachat/deltachat-android/files/7576829/2021.11.21-DC_Mausi.log.txt)
- Logs: attached

**Comment by Hocuri** [comment]
TLDR: I'll create a PR.

Can reproduce in Android 11 emulator. 

Stacktrace:

```
2021-11-21 21:57:52.904 9646-9646/com.b44t.messenger.beta E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.b44t.messenger.beta, PID: 9646
    java.lang.SecurityException: getDataNetworkTypeForSubscriber
        at android.os.Parcel.createExceptionOrNull(Parcel.java:2373)
        at android.os.Parcel.createException(Parcel.java:2357)
        at android.os.Parcel.readException(Parcel.java:2340)
        at android.os.Parcel.readException(Parcel.java:2282)
        at com.android.internal.telephony.ITelephony$Stub$Proxy.getNetworkTypeForSubscriber(ITelephony.java:8762)
        at android.telephony.TelephonyManager.getNetworkType(TelephonyManager.java:3021)
        at android.telephony.TelephonyManager.getNetworkType(TelephonyManager.java:2985)
        at com.mapbox.android.telemetry.TelemetryUtils.obtainCellularNetworkType(TelemetryUtils.java:165)
        at com.mapbox.mapboxsdk.module.telemetry.PhoneState.<init>(PhoneState.java:39)
        at com.mapbox.mapboxsdk.module.telemetry.TelemetryImpl.onAppUserTurnstileEvent(TelemetryImpl.java:46)
        at com.mapbox.mapboxsdk.maps.MapView.onCreate(MapView.java:303)
        at org.thoughtcrime.securesms.map.DCMapFragment.onViewCreated(DCMapFragment.java:117)
        at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:332)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1187)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1356)
        at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:1434)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1497)
        at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:447)
        at androidx.fragment.app.FragmentManager.executeOps(FragmentManager.java:2169)
        at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1992)
        at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1947)
        at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1849)
        at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2629)
        at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:2577)
        at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:247)
        at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:541)
        at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1435)
        at android.app.Activity.performStart(Activity.java:8018)
        at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3475)
        at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
        at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

BTW, I thought we disabled telemetry??

https://github.com/mapbox/mapbox-navigation-android/issues/3577 suggests that we should add 

```
"com.mapbox.mapboxsdk:mapbox-android-telemetry:6.1.0"
```

as a dependency, and I can confirm that it would help. I'm hesitating though as it would be kinda weird to add a telemetry dependency if we don't want it...

Anyway, it seems to help to just catch the Exception, so I'll just do this.

**Comment by link2xt** [comment]
Probably makes sense to evaluate how difficult it is to switch to https://maplibre.org/
