### ISSUE TITLE
app crashes when exporting attachment

### ISSUE THREAD

**Issue by adbenitez** [deltachat/deltachat-android#2270]
if you export an attachment, then go to the folder and delete it, then go to delta chat and try to export it again, the app crashes, the attachment is saved

- Android version: 11
- Delta Chat version: 1.29.0
- Steps to reproduce the problem:
   1. select attachment in delta chat and export it
   2. go to your file explorer and delete the exported file
   3. go to delta chat again and try to export the same file
   4. delta chat crashes, file is exported anyway 
- Logs:
```
04-09 16:42:06.124  5981 13193 E DatabaseUtils: Writing exception to parcel                                                                                                                                                      
04-09 16:42:06.124  5981 13193 E DatabaseUtils: android.database.sqlite.SQLiteConstraintException: UNIQUE constraint failed: files._data (code 2067 SQLITE_CONSTRAINT_UNIQUE[2067])                                              
04-09 16:42:06.124  5981 13193 E DatabaseUtils:         at android.database.sqlite.SQLiteConnection.nativeExecuteForChangedRowCount(Native Method)
04-09 16:42:06.124  5981 13193 E DatabaseUtils:         at android.database.sqlite.SQLiteConnection.executeForChangedRowCount(SQLiteConnection.java:1164)
04-09 16:42:06.124  5981 13193 E DatabaseUtils:         at android.database.sqlite.SQLiteSession.executeForChangedRowCount(SQLiteSession.java:756)
04-09 16:42:06.124  5981 13193 E DatabaseUtils:         at android.database.sqlite.SQLiteStatement.executeUpdateDelete(SQLiteStatement.java:66)
04-09 16:42:06.124  5981 13193 E DatabaseUtils:         at com.android.providers.media.util.DatabaseUtils.executeUpdateDelete(DatabaseUtils.java:468)
04-09 16:42:06.124  5981 13193 E DatabaseUtils:         at com.android.providers.media.util.SQLiteQueryBuilder.update(SQLiteQueryBuilder.java:697)
04-09 16:42:06.124  5981 13193 E DatabaseUtils:         at com.android.providers.media.util.SQLiteQueryBuilder.lambda$update$2(SQLiteQueryBuilder.java:619)
04-09 16:42:06.124  5981 13193 E DatabaseUtils:         at com.android.providers.media.util.SQLiteQueryBuilder.lambda$update$2$SQLiteQueryBuilder(Unknown Source:0)                                 
04-09 16:42:06.124  5981 13193 E DatabaseUtils:         at com.android.providers.media.util.-$$Lambda$SQLiteQueryBuilder$AgEfPRRGX0oz5jjY6qV0HE57T3E.apply(Unknown Source:10)
04-09 16:42:06.124  5981 13193 E DatabaseUtils:         at com.android.providers.media.DatabaseHelper.runWithTransaction(DatabaseHelper.java:573)
04-09 16:42:06.124  5981 13193 E DatabaseUtils:         at com.android.providers.media.util.SQLiteQueryBuilder.update(SQLiteQueryBuilder.java:618)
04-09 16:42:06.124  5981 13193 E DatabaseUtils:         at com.android.providers.media.MediaProvider.lambda$updateAllowingReplace$25(MediaProvider.java:5784)
04-09 16:42:06.124  5981 13193 E DatabaseUtils:         at com.android.providers.media.MediaProvider.lambda$updateAllowingReplace$25$MediaProvider(Unknown Source:0)
04-09 16:42:06.124  5981 13193 E DatabaseUtils:         at com.android.providers.media.-$$Lambda$MediaProvider$MKqBLjeqJzRznq_qwlNQl_bhmj4.apply(Unknown Source:15)
04-09 16:42:06.124  5981 13193 E DatabaseUtils:         at com.android.providers.media.DatabaseHelper.runWithTransaction(DatabaseHelper.java:578)
04-09 16:42:06.124  5981 13193 E DatabaseUtils:         at com.android.providers.media.MediaProvider.updateAllowingReplace(MediaProvider.java:5782)
04-09 16:42:06.124  5981 13193 E DatabaseUtils:         at com.android.providers.media.MediaProvider.updateInternal(MediaProvider.java:5731)
04-09 16:42:06.124  5981 13193 E DatabaseUtils:         at com.android.providers.media.MediaProvider.update(MediaProvider.java:5305)
04-09 16:42:06.124  5981 13193 E DatabaseUtils:         at android.content.ContentProvider$Transport.update(ContentProvider.java:457)
04-09 16:42:06.124  5981 13193 E DatabaseUtils:         at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:230)
04-09 16:42:06.124  5981 13193 E DatabaseUtils:         at android.os.Binder.execTransactInternal(Binder.java:1190)
04-09 16:42:06.124  5981 13193 E DatabaseUtils:         at android.os.Binder.execTransact(Binder.java:1159)
04-09 16:42:06.134 22862 23012 E AndroidRuntime: FATAL EXCEPTION: AsyncTask #5
04-09 16:42:06.134 22862 23012 E AndroidRuntime: Process: chat.delta.lite, PID: 22862
04-09 16:42:06.134 22862 23012 E AndroidRuntime: java.lang.RuntimeException: An error occurred while executing doInBackground()
04-09 16:42:06.134 22862 23012 E AndroidRuntime:        at android.os.AsyncTask$4.done(AsyncTask.java:415)
04-09 16:42:06.134 22862 23012 E AndroidRuntime:        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
04-09 16:42:06.134 22862 23012 E AndroidRuntime:        at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
04-09 16:42:06.134 22862 23012 E AndroidRuntime:        at java.util.concurrent.FutureTask.run(FutureTask.java:271)
04-09 16:42:06.134 22862 23012 E AndroidRuntime:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
04-09 16:42:06.134 22862 23012 E AndroidRuntime:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
04-09 16:42:06.134 22862 23012 E AndroidRuntime:        at java.lang.Thread.run(Thread.java:923)
04-09 16:42:06.134 22862 23012 E AndroidRuntime: Caused by: android.database.sqlite.SQLiteConstraintException: UNIQUE constraint failed: files._data (code 2067 SQLITE_CONSTRAINT_UNIQUE[2067])
04-09 16:42:06.134 22862 23012 E AndroidRuntime:        at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:178)
04-09 16:42:06.134 22862 23012 E AndroidRuntime:        at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:142)
04-09 16:42:06.134 22862 23012 E AndroidRuntime:        at android.content.ContentProviderProxy.update(ContentProviderNative.java:649)
04-09 16:42:06.134 22862 23012 E AndroidRuntime:        at android.content.ContentResolver.update(ContentResolver.java:2366)
04-09 16:42:06.134 22862 23012 E AndroidRuntime:        at android.content.ContentResolver.update(ContentResolver.java:2328)
04-09 16:42:06.134 22862 23012 E AndroidRuntime:        at org.thoughtcrime.securesms.util.SaveAttachmentTask.saveAttachment(SaveAttachmentTask.java:129)
04-09 16:42:06.134 22862 23012 E AndroidRuntime:        at org.thoughtcrime.securesms.util.SaveAttachmentTask.doInBackground(SaveAttachmentTask.java:74)
04-09 16:42:06.134 22862 23012 E AndroidRuntime:        at org.thoughtcrime.securesms.util.SaveAttachmentTask.doInBackground(SaveAttachmentTask.java:38)
04-09 16:42:06.134 22862 23012 E AndroidRuntime:        at android.os.AsyncTask$3.call(AsyncTask.java:394)
04-09 16:42:06.134 22862 23012 E AndroidRuntime:        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
04-09 16:42:06.134 22862 23012 E AndroidRuntime:        ... 3 more
```

**Comment by gerryfrancis** [comment]
I cannot reproduce that issue with the nightly build of 2022-04-11.

**Comment by AndreaLattmann** [comment]
I followed the steps but with version 1.36.2 I can't replicate the bug

**Comment by adbenitez** [comment]
> org.thoughtcrime.securesms.util.SaveAttachmentTask.saveAttachment

I also can no longer reproduce it, it is an old issue maybe it was fixed as side effect of other code changes
