### ISSUE TITLE
Crash when notification sound is unavailabe

### ISSUE THREAD

**Issue by hurzl** [deltachat/deltachat-android#2363]
- Android version: 12

- Delta Chat version: 1.30.3
- Expected behavior: ignore or error message
- Actual behavior: crash on every incoming message
- Steps to reproduce the problem: deinstall a previously used sounds package where the current sound was picked from

- Logs: `java.lang.SecurityException: UID 10139 does not have permission to content://media/external_primary/audio/media/26320?title=Paper%20Clip&canonical=1
`

**Comment by Hocuri** [comment]
Thanks for the bug report?

Is there a complete stack trace in the logs?

**Comment by hurzl** [comment]
only this
```
08-08 10:44:13.990  9528  9561 E AndroidRuntime: FATAL EXCEPTION: eventThread
08-08 10:44:13.990  9528  9561 E AndroidRuntime: Process: com.b44t.messenger, PID: 9528
08-08 10:44:13.990  9528  9561 E AndroidRuntime: java.lang.SecurityException: UID 10139 does not have permission to content://media/external_primary/audio/media/26320?title=Paper%20Clip&canonical=1 [user 0]
08-08 10:44:13.990  9528  9561 E AndroidRuntime:        at android.os.Parcel.createExceptionOrNull(Parcel.java:2426)
08-08 10:44:13.990  9528  9561 E AndroidRuntime:        at android.os.Parcel.createException(Parcel.java:2410)
08-08 10:44:13.990  9528  9561 E AndroidRuntime:        at android.os.Parcel.readException(Parcel.java:2393)
08-08 10:44:13.990  9528  9561 E AndroidRuntime:        at android.os.Parcel.readException(Parcel.java:2335)
08-08 10:44:13.990  9528  9561 E AndroidRuntime:        at android.app.INotificationManager$Stub$Proxy.enqueueNotificationWithTag(INotificationManager.java:3421)
08-08 10:44:13.990  9528  9561 E AndroidRuntime:        at android.app.NotificationManager.notifyAsUser(NotificationManager.java:677)
08-08 10:44:13.990  9528  9561 E AndroidRuntime:        at android.app.NotificationManager.notify(NotificationManager.java:627)
08-08 10:44:13.990  9528  9561 E AndroidRuntime:        at androidx.core.app.NotificationManagerCompat.notify(NotificationManagerCompat.java:215)
08-08 10:44:13.990  9528  9561 E AndroidRuntime:        at androidx.core.app.NotificationManagerCompat.notify(NotificationManagerCompat.java:199)
08-08 10:44:13.990  9528  9561 E AndroidRuntime:        at org.thoughtcrime.securesms.notifications.NotificationCenter.lambda$addNotification$0$org-thoughtcrime-securesms-notifications-NotificationCenter(NotificationCenter.java:487)
08-08 10:44:13.990  9528  9561 E AndroidRuntime:        at org.thoughtcrime.securesms.notifications.NotificationCenter$$ExternalSyntheticLambda1.run(Unknown Source:6)
08-08 10:44:13.990  9528  9561 E AndroidRuntime:        at org.thoughtcrime.securesms.util.Util.runOnAnyBackgroundThread(Util.java:237)
08-08 10:44:13.990  9528  9561 E AndroidRuntime:        at org.thoughtcrime.securesms.notifications.NotificationCenter.addNotification(NotificationCenter.java:314)
08-08 10:44:13.990  9528  9561 E AndroidRuntime:        at org.thoughtcrime.securesms.connect.DcEventCenter.handleEvent(DcEventCenter.java:163)
08-08 10:44:13.990  9528  9561 E AndroidRuntime:        at org.thoughtcrime.securesms.ApplicationContext.lambda$onCreate$1$org-thoughtcrime-securesms-ApplicationContext(ApplicationContext.java:111)
08-08 10:44:13.990  9528  9561 E AndroidRuntime:        at org.thoughtcrime.securesms.ApplicationContext$$ExternalSyntheticLambda1.run(Unknown Source:2)
08-08 10:44:13.990  9528  9561 E AndroidRuntime:        at java.lang.Thread.run(Thread.java:920)
08-08 10:44:13.990  9528  9561 E AndroidRuntime: Caused by: android.os.RemoteException: Remote stack trace:
08-08 10:44:13.990  9528  9561 E AndroidRuntime:        at com.android.server.uri.UriGrantsManagerService.checkGrantUriPermissionUnlocked(UriGrantsManagerService.java:1254)
08-08 10:44:13.990  9528  9561 E AndroidRuntime:        at com.android.server.uri.UriGrantsManagerService.checkGrantUriPermissionUnlocked(UriGrantsManagerService.java:1268)
08-08 10:44:13.990  9528  9561 E AndroidRuntime:        at com.android.server.uri.UriGrantsManagerService.access$900(UriGrantsManagerService.java:107)
08-08 10:44:13.990  9528  9561 E AndroidRuntime:        at com.android.server.uri.UriGrantsManagerService$LocalService.checkGrantUriPermission(UriGrantsManagerService.java:1402)
08-08 10:44:13.990  9528  9561 E AndroidRuntime:        at com.android.server.notification.NotificationRecord.visitGrantableUri(NotificationRecord.java:1354)

```

**Comment by Hocuri** [comment]
Thanks!
Can't fix this right now, writing down what I know so that I remember it:

- This only happens on Android 7 and below
- Code similar to this one might fix it:
```diff
diff --git a/src/org/thoughtcrime/securesms/notifications/NotificationCenter.java b/src/org/thoughtcrime/securesms/notifications/NotificationCenter.java
index 6ea55e708..ed5c2fef4 100644
--- a/src/org/thoughtcrime/securesms/notifications/NotificationCenter.java
+++ b/src/org/thoughtcrime/securesms/notifications/NotificationCenter.java
@@ -40,6 +40,7 @@ import org.thoughtcrime.securesms.util.BitmapUtil;
 import org.thoughtcrime.securesms.util.Prefs;
 import org.thoughtcrime.securesms.util.Util;
 
+import java.io.InputStream;
 import java.math.BigInteger;
 import java.security.MessageDigest;
 import java.util.ArrayList;
@@ -380,7 +381,13 @@ public class NotificationCenter {
                 if (signal) {
                     Uri sound = effectiveSound(chatId);
                     if (sound != null && !TextUtils.isEmpty(sound.toString())) {
+                        try {
+                            InputStream inputStream = context.getContentResolver().openInputStream(uri);
+                            inputStream.close();
                             builder.setSound(sound);
+                        } catch (Exception e) {
+                            Log.w(MY_TAG, "File corresponding to the uri does not exist " + uri.toString());
+                        }
                     }
                     boolean vibrate = effectiveVibrate(chatId);
                     if (vibrate) {
```

**Comment by Hocuri** [comment]
In the meantime, @hurzl how do I install such a sound package?

**Comment by hurzl** [comment]
is just checking for `new File(sound.getPath()).exists()` too simple?

**Comment by Hocuri** [comment]
Ah, yes, this should work too since it only needs to work on older Androids, anyway (since API 30 you can't use the File API anymore for storage you don't own)

**Comment by hurzl** [comment]
You mean the fix above is only for Android 7 or below?

**Comment by Hocuri** [comment]
Yes, and ah, you wrote "Android 12" above, I must have overlooked something

**Comment by adbenitez** [comment]
I also tried to reproduce selecting a file and then moving the file elsewhere but it doesn't crash,
can you provide a "ringtones app" like the one you used @hurzl ? tried searching for such kind of app in F-Droid but found nothing

**Comment by hurzl** [comment]
How do you select a file? I can only select from a list of ringtones. 
I also don't see ringtones on F-Droid, but in the Google Playstore.

**Comment by adbenitez** [comment]
closing this stale issue as so far have not found any app like that on F-Droid and couldn't reproduce
