### ISSUE TITLE
Crash when attaching media while using special developer options

### ISSUE THREAD

**Issue by syxie** [deltachat/deltachat-android#255]
Using v0.14.0, clicking on the paperclip icon from within a chat results in a Telegram-like attachment page, but this is only briefly shown as it crashes instantly afterward.

I'm using a Sony G8441 (Xperia XZ1 Compact) on Android 8.0.0 on kernel version 4.4.78-perf and build number 47.1.A.12.75.

**Steps to reproduce the problem**

1. Open a chat
2. Click the paperclip icon to attach media

Logcat yields nothing after "02-28 17:43:40.338 I/DeltaChat( 6229): T3: IDLE start..."

**Comment by r10s** [comment]
has someone the same problem on other Android 8 / Oreo devices?

**Comment by noerw** [comment]
Having this issue as well on Moto Z, Android 8.0.0.
Was logging changed to be more verbose since then? If so, I'm happy to check my logcat

**Comment by r10s** [comment]
Delta Chat logging is rather verbose, however, such crashes are typically logged by the system, in either way, a log would be very interesting :)

**Comment by noerw** [comment]
logcat attached
<details>

```
05-01 21:47:04.350   713   713 D SurfaceFlinger: duplicate layer name: changing com.b44t.messenger/com.b44t.messenger.LaunchActivity to com.b44t.messenger/com.b44t.messenger.LaunchActivity#1
05-01 21:47:04.373 27761 27782 V MiniThumbFile: Translate to actual pos -1 from 53646
05-01 21:47:04.424  2254  2269 W ExifInterface: Skip the tag entry since tag number is not defined: 2
05-01 21:47:04.493 27761 27782 V MiniThumbFile: Translate to actual pos -1 from 53647
05-01 21:47:04.501 27761 27761 D AndroidRuntime: Shutting down VM
05-01 21:47:04.502 27761 27761 E AndroidRuntime: FATAL EXCEPTION: main
05-01 21:47:04.502 27761 27761 E AndroidRuntime: Process: com.b44t.messenger, PID: 27761
05-01 21:47:04.502 27761 27761 E AndroidRuntime: java.lang.IllegalStateException: Animator has already started, cannot change it now!
05-01 21:47:04.502 27761 27761 E AndroidRuntime:        at android.view.RenderNodeAnimator.checkMutable(RenderNodeAnimator.java:149)
05-01 21:47:04.502 27761 27761 E AndroidRuntime:        at android.view.RenderNodeAnimator.setDuration(RenderNodeAnimator.java:324)
05-01 21:47:04.502 27761 27761 E AndroidRuntime:        at android.view.RenderNodeAnimator.setDuration(RenderNodeAnimator.java:322)
05-01 21:47:04.502 27761 27761 E AndroidRuntime:        at android.animation.AnimatorSet.updateAnimatorsDuration(AnimatorSet.java:774)
05-01 21:47:04.502 27761 27761 E AndroidRuntime:        at android.animation.AnimatorSet.getTotalDuration(AnimatorSet.java:1735)
05-01 21:47:04.502 27761 27761 E AndroidRuntime:        at android.animation.AnimatorSet.forceToEnd(AnimatorSet.java:446)
05-01 21:47:04.502 27761 27761 E AndroidRuntime:        at android.animation.AnimatorSet.doAnimationFrame(AnimatorSet.java:995)
05-01 21:47:04.502 27761 27761 E AndroidRuntime:        at android.animation.AnimationHandler.doAnimationFrame(AnimationHandler.java:146)
05-01 21:47:04.502 27761 27761 E AndroidRuntime:        at android.animation.AnimationHandler.-wrap2(Unknown Source:0)
05-01 21:47:04.502 27761 27761 E AndroidRuntime:        at android.animation.AnimationHandler$1.doFrame(AnimationHandler.java:54)
05-01 21:47:04.502 27761 27761 E AndroidRuntime:        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:909)
05-01 21:47:04.502 27761 27761 E AndroidRuntime:        at android.view.Choreographer.doCallbacks(Choreographer.java:723)
05-01 21:47:04.502 27761 27761 E AndroidRuntime:        at android.view.Choreographer.doFrame(Choreographer.java:655)
05-01 21:47:04.502 27761 27761 E AndroidRuntime:        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)
05-01 21:47:04.502 27761 27761 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:789)
05-01 21:47:04.502 27761 27761 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:98)
05-01 21:47:04.502 27761 27761 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:164)
05-01 21:47:04.502 27761 27761 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:6592)
05-01 21:47:04.502 27761 27761 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
05-01 21:47:04.502 27761 27761 E AndroidRuntime:        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
05-01 21:47:04.502 27761 27761 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:769)
05-01 21:47:04.506  1449  2588 W ActivityManager:   Force finishing activity com.b44t.messenger/.LaunchActivity
05-01 21:47:04.518  1449  1471 I ActivityManager: Showing crash dialog for package com.b44t.messenger u0
05-01 21:47:04.545  2254  2269 W ExifInterface: Skip the tag entry since tag number is not defined: 2
05-01 21:47:04.598 27761 27782 V MiniThumbFile: Translate to actual pos -1 from 53644
05-01 21:47:04.615  2254  2269 W ExifInterface: Skip the tag entry since tag number is not defined: 2
05-01 21:47:04.665   713   845 I SFPerfTracer:      triggers: (rate: 44:2007) (209442 sw vsyncs) (0 skipped) (1:1515504 vsyncs) (3:2294019)
05-01 21:47:04.723 27761 27782 V MiniThumbFile: Translate to actual pos -1 from 53645
05-01 21:47:04.751  2254  2269 W ExifInterface: Skip the tag entry since tag number is not defined: 2
05-01 21:47:04.842 27761 27782 V MiniThumbFile: Translate to actual pos -1 from 53643
05-01 21:47:04.866  2254  2269 W ExifInterface: Skip the tag entry since tag number is not defined: 2
05-01 21:47:05.014  1449  1470 W ActivityManager: Activity pause timeout for ActivityRecord{b41966b u0 com.b44t.messenger/.LaunchActivity t4627 f}
05-01 21:47:05.029  1449  1470 I ActivityManager: moveHomeStack, setupComplete:true
05-01 21:47:05.380  6494  6494 I MotoDisplay: Acquiring wakelock
05-01 21:47:05.382  6494  6494 I MotoDisplay: Releasing wakelock
05-01 21:47:05.510  2366  2379 I zygote64: NativeAllocBackground concurrent copying GC freed 35174(1374KB) AllocSpace objects, 0(0B) LOS objects, 49% free, 9MB/19MB, paused 346us total 146.243ms
05-01 21:47:05.622  1449  1458 I zygote64: NativeAllocBackground concurrent copying GC freed 29223(1571KB) AllocSpace objects, 13(800KB) LOS objects, 42% free, 19MB/33MB, paused 705us total 207.363ms
05-01 21:47:06.079  7248  7669 D PlatformAlarmService: Run job, request{id=1079, tag=FilesSyncJob, transient=false}, waited 00:00:00, delay 00:00:00
05-01 21:47:06.094  7248  7669 I JobExecutor: Executing request{id=1079, tag=FilesSyncJob, transient=false}, context PlatformAlarmService
05-01 21:47:06.114  7248  7670 I JobExecutor: Finished job{id=1079, finished=true, result=SUCCESS, canceled=false, periodic=false, class=FilesSyncJob, tag=FilesSyncJob}
05-01 21:47:06.116  7248  7669 D PlatformAlarmService: Finished job, request{id=1079, tag=FilesSyncJob, transient=false} SUCCESS
```
</details>

**Comment by Hocceruser** [comment]
Apparently, others also have this problem: https://stackoverflow.com/questions/45419378/disabling-animations-on-a-device-crashes-the-app and https://github.com/osmandapp/Osmand/issues/5006

There even are answers to the StackOverflow question but I do not know if whoever wrote them was right. 
If the first answer _is_ true, many of these classes will probably have to be changed: https://github.com/search?q=org%3Adeltachat+setDuration&type=Code

**Comment by r10s** [comment]
@Hocceruser these are good information, would be interested what Telegram-FOSS has done to fix it. I think we can do the same in Delta then.

**Comment by noerw** [comment]
I am infamiliar with both the deltachat and telegram android codebases, but after a quick dig, the following method seems to be responsible. Especially the `parentLayout.animationInProgress` checks and trycatch blocks seem related.

https://github.com/Telegram-FOSS-Team/Telegram-FOSS/blob/f2cdfecef789cd51d427232e94ad2ef6efa91a71/TMessagesProj/src/main/java/org/telegram/ui/ActionBar/BaseFragment.java#L311-L321

**Comment by r10s** [comment]
just trying to reproduce the crash in the Emulator using Android 8.1 API 27. Unfortunately, i cannot reproduce the bug there :/

**Comment by r10s** [comment]
> Especially the parentLayout.animationInProgress checks and trycatch blocks seem related.

@noerw do you have more information about this? what do you think should be changed? the other sources push us more to the direction of AnimatorSet.setDuration()

**Comment by noerw** [comment]
Hah I found the cause.
It only happens when `animator duration scale` is set to `off` under developer options in android settings.
I did this a while ago to make my ui snappier.

Telegram FOSS 4.6.0b works well even with that setting.
So, it's not as critical, but it would be nice if this was fixed. I will see if I can look into it in the next days

**Comment by r10s** [comment]
@noerw perfect :) \o/ \o/ \o/

**Comment by r10s** [comment]
>  I will see if I can look into it in the next days

that would be great :)

**Comment by Hocceruser** [comment]
OsmAND has closed the issue in this commit: https://github.com/osmandapp/Osmand/commit/431f1d58a0abb69d54a0fac166d9820968c35bba
