### ISSUE TITLE
crash when opening the log (on older androids in emulator)

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-android#2899]
reason is that `grabLogcat()` may return `null` which is not handled

when on that: the whole `Scrubber` class seems to be not needed.

<details>
I/ListPopupWindow: Could not find method setEpicenterBounds(Rect) on PopupWindow. Oh well.
W/art: Before Android 4.1, method int androidx.appcompat.widget.DropDownListView.lookForSelectablePosition(int, boolean) would have incorrectly overridden the package-private method in android.widget.ListView
W/art: Before Android 4.1, method int androidx.appcompat.widget.MenuPopupWindow$MenuDropDownListView.lookForSelectablePosition(int, boolean) would have incorrectly overridden the package-private method in android.widget.ListView
D/EGL_emulation: eglMakeCurrent: 0x7c145a7200: ver 3 0 (tinfo 0x7c145b1ac0)
D/EGL_emulation: eglMakeCurrent: 0x7c145a7200: ver 3 0 (tinfo 0x7c145b1ac0)
D/EGL_emulation: eglMakeCurrent: 0x7c145a7200: ver 3 0 (tinfo 0x7c145b1ac0)
D/EGL_emulation: eglMakeCurrent: 0x7c145a7200: ver 3 0 (tinfo 0x7c145b1ac0)
D/EGL_emulation: eglMakeCurrent: 0x7c145a7200: ver 3 0 (tinfo 0x7c145b1ac0)
I/ConversationListFragment: �� pausing chatlist: cancel update timer
W/PassphraseRequiredActionBarActivity: onCreate(null)
D/EGL_emulation: eglMakeCurrent: 0x7c145a7200: ver 3 0 (tinfo 0x7c145b1ac0)
W/PassphraseRequiredActionBarActivity: onCreate(null)
I/WebViewFactory: Loading com.android.webview version 37 (8789838-arm64) (code 100002)
I/LibraryLoader: Loading: webviewchromium
I/LibraryLoader: Time to load native libraries: 1 ms (timestamps 5300-5301)
I/LibraryLoader: Expected native library version number "",actual native library version number ""
W/WebViewActivity: Cannot set WebView proxy.
V/WebViewChromiumFactoryProvider: Binding Chromium to main looper Looper (main, tid 1) {d687929}
I/LibraryLoader: Expected native library version number "",actual native library version number ""
I/chromium: [INFO:library_loader_hooks.cc(106)] Chromium logging enabled: level = 0, default verbosity = 0
I/BrowserStartupController: Initializing chromium process, renderers=0
W/art: Attempt to remove local handle scope entry from IRT, ignoring
W/AudioManagerAndroid: Requires BLUETOOTH permission
W/chromium: [WARNING:resource_bundle.cc(315)] locale_file_path.empty()
I/chromium: [INFO:aw_browser_main_parts.cc(63)] Load from apk succesful, fd=64 off=46092 len=2953
I/chromium: [INFO:aw_browser_main_parts.cc(78)] Loading webviewchromium.pak from, fd:65 off:228796 len:643667
D/EGL_emulation: eglCreateContext: 0x7c0ab2a980: maj 3 min 0 rcv 3
D/EGL_emulation: eglMakeCurrent: 0x7c0ab2a980: ver 3 0 (tinfo 0x7c0cfcc220)
E/eglCodecCommon: glUtilsParamSize: unknow param 0x00008cdf
E/eglCodecCommon: glUtilsParamSize: unknow param 0x00008824
W/chromium: [WARNING:proxy_service.cc(901)] PAC support disabled because there is no system implementation
W/chromium: [WARNING:data_reduction_proxy_settings.cc(403)] SPDY proxy OFF at startup
W/art: Attempt to remove local handle scope entry from IRT, ignoring
W/AwContents: onDetachedFromWindow called when already detached. Ignoring
D/EGL_emulation: eglMakeCurrent: 0x7c145a7200: ver 3 0 (tinfo 0x7c145b1ac0)
D/EGL_emulation: eglMakeCurrent: 0x7c145a7200: ver 3 0 (tinfo 0x7c145b1ac0)
D/EGL_emulation: eglMakeCurrent: 0x7c145a7200: ver 3 0 (tinfo 0x7c145b1ac0)
D/EGL_emulation: eglMakeCurrent: 0x7c145a7200: ver 3 0 (tinfo 0x7c145b1ac0)
D/EGL_emulation: eglMakeCurrent: 0x7c145a7200: ver 3 0 (tinfo 0x7c145b1ac0)
D/OpenGLRenderer: endAllStagingAnimators on 0x7c0f134c00 (RippleDrawable) with handle 0x7c145b1be0
E/eglCodecCommon: glUtilsParamSize: unknow param 0x000085b5
E/eglCodecCommon: glUtilsParamSize: unknow param 0x000085b5
E/eglCodecCommon: glUtilsParamSize: unknow param 0x000085b5
E/eglCodecCommon: glUtilsParamSize: unknow param 0x000085b5
E/eglCodecCommon: glUtilsParamSize: unknow param 0x000085b5
E/eglCodecCommon: glUtilsParamSize: unknow param 0x000085b5
E/eglCodecCommon: glUtilsParamSize: unknow param 0x000085b5
E/eglCodecCommon: glUtilsParamSize: unknow param 0x000085b5
E/eglCodecCommon: glUtilsParamSize: unknow param 0x000085b5
E/eglCodecCommon: glUtilsParamSize: unknow param 0x000085b5
E/eglCodecCommon: glUtilsParamSize: unknow param 0x000085b5
E/eglCodecCommon: glUtilsParamSize: unknow param 0x000085b5
E/eglCodecCommon: glUtilsParamSize: unknow param 0x000085b5
E/eglCodecCommon: glUtilsParamSize: unknow param 0x000085b5
E/eglCodecCommon: glUtilsParamSize: unknow param 0x000085b5
E/eglCodecCommon: glUtilsParamSize: unknow param 0x000085b5
E/eglCodecCommon: glUtilsParamSize: unknow param 0x000085b5
E/eglCodecCommon: glUtilsParamSize: unknow param 0x000085b5
E/eglCodecCommon: glUtilsParamSize: unknow param 0x000085b5
E/eglCodecCommon: glUtilsParamSize: unknow param 0x000085b5
E/eglCodecCommon: glUtilsParamSize: unknow param 0x000085b5
E/eglCodecCommon: glUtilsParamSize: unknow param 0x000085b5
E/eglCodecCommon: glUtilsParamSize: unknow param 0x000085b5
E/eglCodecCommon: glUtilsParamSize: unknow param 0x000085b5
E/eglCodecCommon: glUtilsParamSize: unknow param 0x000085b5
E/eglCodecCommon: glUtilsParamSize: unknow param 0x000085b5
E/eglCodecCommon: glUtilsParamSize: unknow param 0x000085b5
E/eglCodecCommon: glUtilsParamSize: unknow param 0x000085b5
E/eglCodecCommon: glUtilsParamSize: unknow param 0x000085b5
E/eglCodecCommon: glUtilsParamSize: unknow param 0x000085b5
E/eglCodecCommon: glUtilsParamSize: unknow param 0x000085b5
E/eglCodecCommon: glUtilsParamSize: unknow param 0x000085b5
E/eglCodecCommon: glUtilsParamSize: unknow param 0x000085b5
E/eglCodecCommon: glUtilsParamSize: unknow param 0x000085b5
E/eglCodecCommon: glUtilsParamSize: unknow param 0x000085b5
E/eglCodecCommon: glUtilsParamSize: unknow param 0x000085b5
E/eglCodecCommon: glUtilsParamSize: unknow param 0x000085b5
E/eglCodecCommon: glUtilsParamSize: unknow param 0x000085b5
E/eglCodecCommon: glUtilsParamSize: unknow param 0x000085b5
E/eglCodecCommon: glUtilsParamSize: unknow param 0x000085b5
E/eglCodecCommon: glUtilsParamSize: unknow param 0x000085b5
E/eglCodecCommon: glUtilsParamSize: unknow param 0x000085b5
E/eglCodecCommon: glUtilsParamSize: unknow param 0x000085b5
E/eglCodecCommon: glUtilsParamSize: unknow param 0x000085b5
E/eglCodecCommon: glUtilsParamSize: unknow param 0x000085b5
E/eglCodecCommon: glUtilsParamSize: unknow param 0x000085b5
E/eglCodecCommon: glUtilsParamSize: unknow param 0x000085b5
E/eglCodecCommon: glUtilsParamSize: unknow param 0x000085b5
E/eglCodecCommon: glUtilsParamSize: unknow param 0x000085b5
E/eglCodecCommon: glUtilsParamSize: unknow param 0x000085b5
E/eglCodecCommon: glUtilsParamSize: unknow param 0x000085b5
E/eglCodecCommon: glUtilsParamSize: unknow param 0x000085b5
E/eglCodecCommon: glUtilsParamSize: unknow param 0x000085b5
E/eglCodecCommon: glUtilsParamSize: unknow param 0x000085b5
E/eglCodecCommon: glUtilsParamSize: unknow param 0x000085b5
E/eglCodecCommon: glUtilsParamSize: unknow param 0x000085b5
D/EGL_emulation: eglMakeCurrent: 0x7c145a7200: ver 3 0 (tinfo 0x7c145b1ac0)
D/EGL_emulation: eglMakeCurrent: 0x7c145a7200: ver 3 0 (tinfo 0x7c145b1ac0)
E/eglCodecCommon: glUtilsParamSize: unknow param 0x000085b5
E/eglCodecCommon: glUtilsParamSize: unknow param 0x000085b5
D/EGL_emulation: eglMakeCurrent: 0x7c145a7200: ver 3 0 (tinfo 0x7c145b1ac0)
D/EGL_emulation: eglMakeCurrent: 0x7c145a7200: ver 3 0 (tinfo 0x7c145b1ac0)
E/eglCodecCommon: glUtilsParamSize: unknow param 0x000085b5
E/eglCodecCommon: glUtilsParamSize: unknow param 0x000085b5
D/EGL_emulation: eglMakeCurrent: 0x7c145a7200: ver 3 0 (tinfo 0x7c145b1ac0)
E/eglCodecCommon: glUtilsParamSize: unknow param 0x000085b5
E/eglCodecCommon: glUtilsParamSize: unknow param 0x000085b5
E/eglCodecCommon: glUtilsParamSize: unknow param 0x000085b5
E/eglCodecCommon: glUtilsParamSize: unknow param 0x000085b5
E/eglCodecCommon: glUtilsParamSize: unknow param 0x000085b5
E/eglCodecCommon: glUtilsParamSize: unknow param 0x000085b5
W/ScreenOrientationListener: Removing an inexistent observer!
D/EGL_emulation: eglMakeCurrent: 0x7c145a7200: ver 3 0 (tinfo 0x7c145b1ac0)
W/ProcessManager: waitpid on failed exec failed: No child processes
W/LogViewFragment: IOException when trying to read logcat.
    java.io.IOException: Error running exec(). Command: [logcat, -v, threadtime, -d] Working Directory: null Environment: null
        at java.lang.ProcessManager.exec(ProcessManager.java:211)
        at java.lang.Runtime.exec(Runtime.java:173)
        at java.lang.Runtime.exec(Runtime.java:246)
        at java.lang.Runtime.exec(Runtime.java:189)
        at org.thoughtcrime.securesms.LogViewFragment.grabLogcat(LogViewFragment.java:139)
        at org.thoughtcrime.securesms.LogViewFragment.access$100(LogViewFragment.java:60)
        at org.thoughtcrime.securesms.LogViewFragment$PopulateLogcatAsyncTask.doInBackground(LogViewFragment.java:169)
        at org.thoughtcrime.securesms.LogViewFragment$PopulateLogcatAsyncTask.doInBackground(LogViewFragment.java:156)
        at android.os.AsyncTask$2.call(AsyncTask.java:288)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
        at java.lang.Thread.run(Thread.java:818)
     Caused by: java.io.IOException: Permission denied
        at java.lang.ProcessManager.exec(Native Method)
        at java.lang.ProcessManager.exec(ProcessManager.java:209)
        at java.lang.Runtime.exec(Runtime.java:173) 
        at java.lang.Runtime.exec(Runtime.java:246) 
        at java.lang.Runtime.exec(Runtime.java:189) 
        at org.thoughtcrime.securesms.LogViewFragment.grabLogcat(LogViewFragment.java:139) 
        at org.thoughtcrime.securesms.LogViewFragment.access$100(LogViewFragment.java:60) 
        at org.thoughtcrime.securesms.LogViewFragment$PopulateLogcatAsyncTask.doInBackground(LogViewFragment.java:169) 
        at org.thoughtcrime.securesms.LogViewFragment$PopulateLogcatAsyncTask.doInBackground(LogViewFragment.java:156) 
        at android.os.AsyncTask$2.call(AsyncTask.java:288) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
        at java.lang.Thread.run(Thread.java:818) 
D/Scrubber: scrubbing input
E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #4
    Process: com.b44t.messenger.beta, PID: 20184
    java.lang.RuntimeException: An error occured while executing doInBackground()
        at android.os.AsyncTask$3.done(AsyncTask.java:300)
        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
        at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
        at java.util.concurrent.FutureTask.run(FutureTask.java:242)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
        at java.lang.Thread.run(Thread.java:818)
     Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'int java.lang.CharSequence.length()' on a null object reference
        at java.util.regex.Matcher.reset(Matcher.java:177)
        at java.util.regex.Matcher.<init>(Matcher.java:90)
        at java.util.regex.Pattern.matcher(Pattern.java:297)
        at org.thoughtcrime.securesms.util.Scrubber.scrub(Scrubber.java:49)
        at org.thoughtcrime.securesms.LogViewFragment$PopulateLogcatAsyncTask.doInBackground(LogViewFragment.java:169)
        at org.thoughtcrime.securesms.LogViewFragment$PopulateLogcatAsyncTask.doInBackground(LogViewFragment.java:156)
        at android.os.AsyncTask$2.call(AsyncTask.java:288)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
        at java.lang.Thread.run(Thread.java:818) 
D/EGL_emulation: eglMakeCurrent: 0x7c145a7200: ver 3 0 (tinfo 0x7c145b1ac0)
D/EGL_emulation: eglMakeCurrent: 0x7c145a7200: ver 3 0 (tinfo 0x7c145b1ac0)
D/EGL_emulation: eglMakeCurrent: 0x7c145a7200: ver 3 0 (tinfo 0x7c145b1ac0)
D/EGL_emulation: eglMakeCurrent: 0x7c145a7200: ver 3 0 (tinfo 0x7c145b1ac0)
D/EGL_emulation: eglMakeCurrent: 0x7c145a7200: ver 3 0 (tinfo 0x7c145b1ac0)
D/EGL_emulation: eglMakeCurrent: 0x7c145a7200: ver 3 0 (tinfo 0x7c145b1ac0)
I/ConversationListFragment: �� resuming chatlist: starting update timer
D/EGL_emulation: eglMakeCurrent: 0x7c145a7200: ver 3 0 (tinfo 0x7c145b1ac0)
D/EGL_emulation: eglMakeCurrent: 0x7c145a7200: ver 3 0 (tinfo 0x7c145b1ac0)
I/ConversationListFragment: �� update timer: refreshing chatlist
D/EGL_emulation: eglMakeCurrent: 0x7c145a7200: ver 3 0 (tinfo 0x7c145b1ac0)
D/EGL_emulation: eglMakeCurrent: 0x7c145a7200: ver 3 0 (tinfo 0x7c145b1ac0)
D/OpenGLRenderer: endAllStagingAnimators on 0x7c08e0d400 (RippleDrawable) with handle 0x7c0ab8a1e0
D/EGL_emulation: eglMakeCurrent: 0x7c145a7200: ver 3 0 (tinfo 0x7c145b1ac0)
D/EGL_emulation: eglMakeCurrent: 0x7c145a7200: ver 3 0 (tinfo 0x7c145b1ac0)
</details>

**Comment by Mgonzalez-droid** [comment]
I am open to work this if needed.

**Comment by Mgonzalez-droid** [comment]
No problem, I will be sure to get this addressed for you! Any preference on where I branch from?

**Comment by r10s** [comment]
> Any preference on where I branch from?

just branch from `main`

nb: for further information about PRs etc., we've just written a brand-new [CONTRIBUTING.md](https://github.com/deltachat/deltachat-android/blob/main/CONTRIBUTING.md) - of course, if questions are left open, feel free to ask here

**Comment by Mgonzalez-droid** [comment]
Sounds great! I'll be sure to read the docs, and let you know if any other questions come up 👍
