### ISSUE TITLE
Can't export key, bad "success" message

### ISSUE THREAD

**Issue by phmarek** [deltachat/deltachat-android#739]
- Platform (android/blackberry/anbox): Android, lineageos 7.1.2
- Device: i9300
- Delta Chat Version: 0.101.1

- Expected behavior:
Export works, no error message;
or export fails, error message

- Actual behavior:
when trying to export the private key DC tells me "successfully exported", but at the same time another popup says "Can't write to /sdcard...". So it looks as if the error code from opening the file isn't really used and that the "success" message is just always printed.

Why the export doesn't work is a different problem... the directory is `0771 root:sdcard_rw`, the DC process doesn't have the `sdcard_rw` group although the app permissions include read and write external memory, and both have been used 22 times.

Perhaps the path to export to should be configurable as well??

- Steps to reproduce the problem: settings => extended => manage keys => export
- Screenshots: attached
- Logs:

strace looks like that:

```
18736 12:21:37.287605 writev(31, [{"\0000I\301,q\\\326\331!\21", 11}, {"\4", 1}, {"DeltaChat\0", 10}, {"Exporting key /storage/emulated/0/Download/public-key-default.asc\0", 66}], 4 <unfinish
ed ...>
18736 12:21:37.288622 <... writev resumed> ) = 88
18736 12:21:37.288701 fstatat64(AT_FDCWD, "/storage/emulated/0/Download/public-key-default.asc", 0x5fd17ca0, AT_SYMLINK_NOFOLLOW) = -1 ENOENT (No such file or directory)
18736 12:21:37.289225 clock_gettime(CLOCK_REALTIME, {1550920897, 289264417}) = 0
18736 12:21:37.289347 getuid32()        = 10074
18736 12:21:37.289433 writev(31, [{"\0000I\301,q\\!\323=\21", 11}, {"\5", 1}, {"DeltaChat\0", 10}, {"Cannot delete \"/storage/emulated/0/Download/public-key-default.asc\".\0", 69}], 4) = 91
18736 12:21:37.289897 openat(AT_FDCWD, "/storage/emulated/0/Download/public-key-default.asc", O_WRONLY|O_CREAT|O_TRUNC|O_LARGEFILE, 0666) = -1 EACCES (Permission denied)
18736 12:21:37.292707 clock_gettime(CLOCK_REALTIME, {1550920897, 292737251}) = 0
18736 12:21:37.292819 getuid32()        = 10074
18736 12:21:37.292954 writev(31, [{"\0000I\301,q\\\343\320r\21", 11}, {"\5", 1}, {"DeltaChat\0", 10}, {"Cannot open \"/storage/emulated/0/Download/public-key-default.asc\" for writing.\0", 79
}], 4) = 101
18736 12:21:37.293418 clock_gettime(CLOCK_REALTIME, {1550920897, 293453584}) = 0
18736 12:21:37.293539 getuid32()        = 10074
18736 12:21:37.293625 writev(31, [{"\0000I\301,q\\\20\277}\21", 11}, {"\6", 1}, {"DeltaChat\0", 10}, {"Cannot write key to /storage/emulated/0/Download/public-key-default.asc\0", 72}], 4 <unf
inished ...>
18736 12:21:37.304402 <... writev resumed> ) = 94
18736 12:21:37.304564 clock_gettime(CLOCK_MONOTONIC, {29890, 294703955}) = 0
18736 12:21:37.304821 clock_gettime(CLOCK_REALTIME,  <unfinished ...>
18736 12:21:37.305659 <... clock_gettime resumed> {1550920897, 304855876}) = 0
18736 12:21:37.305736 getuid32()        = 10074
18736 12:21:37.305822 writev(31, [{"\0000I\301,q\\D\273+\22", 11}, {"\4", 1}, {"DeltaChat\0", 10}, {"Exporting key /storage/emulated/0/Download/private-key-default.asc\0", 67}], 4) = 89
18736 12:21:37.306180 fstatat64(AT_FDCWD, "/storage/emulated/0/Download/private-key-default.asc", 0x5fd17ca0, AT_SYMLINK_NOFOLLOW) = -1 ENOENT (No such file or directory)
18736 12:21:37.306681 clock_gettime(CLOCK_REALTIME, {1550920897, 306716460}) = 0
18736 12:21:37.306799 getuid32()        = 10074
18736 12:21:37.306885 writev(31, [{"\0000I\301,q\\,\37H\22", 11}, {"\5", 1}, {"DeltaChat\0", 10}, {"Cannot delete \"/storage/emulated/0/Download/private-key-default.asc\".\0", 70}], 4 <unfini
shed ...>
18736 12:21:37.309394 <... writev resumed> ) = 92
18736 12:21:37.309756 clock_gettime(CLOCK_MONOTONIC, {29890, 299893121}) = 0
18736 12:21:37.310005 openat(AT_FDCWD, "/storage/emulated/0/Download/private-key-default.asc", O_WRONLY|O_CREAT|O_TRUNC|O_LARGEFILE, 0666) = -1 EACCES (Permission denied)
18736 12:21:37.321243 clock_gettime(CLOCK_REALTIME, {1550920897, 321273585}) = 0
18736 12:21:37.321360 getuid32()        = 10074
18736 12:21:37.321446 writev(31, [{"\0000I\301,q\\\361>&\23", 11}, {"\5", 1}, {"DeltaChat\0", 10}, {"Cannot open \"/storage/emulated/0/Download/private-key-default.asc\" for writing.\0", 80}]
, 4 <unfinished ...>
18736 12:21:37.322476 <... writev resumed> ) = 102
18736 12:21:37.322645 clock_gettime(CLOCK_REALTIME, {1550920897, 322680543}) = 0
18736 12:21:37.322764 getuid32()        = 10074
18736 12:21:37.322849 writev(31, [{"\0000I\301,q\\\337\266;\23", 11}, {"\6", 1}, {"DeltaChat\0", 10}, {"Cannot write key to /storage/emulated/0/Download/private-key-default.asc\0", 73}], 4) =
 95
18736 12:21:37.323233 clock_gettime(CLOCK_MONOTONIC, {29890, 313369830}) = 0
18736 12:21:37.323394 clock_gettime(CLOCK_MONOTONIC, {29890, 313528080}) = 0
```

logcat entries that seem related:
```
02-23 12:26:34.723 18718 18718 E WindowManager:
02-23 12:26:34.723 18718 18718 E WindowManager: android.view.WindowLeaked: Activity org.thoughtcrime.securesms.ApplicationPreferencesActivity has leaked window DecorView@f18c4ad[] that was originally added here
02-23 12:26:34.723 18718 18718 E WindowManager:         at android.view.ViewRootImpl.<init>(ViewRootImpl.java:418)
02-23 12:26:34.723 18718 18718 E WindowManager:         at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:331)
02-23 12:26:34.723 18718 18718 E WindowManager:         at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:94)
02-23 12:26:34.723 18718 18718 E WindowManager:         at android.app.Dialog.show(Dialog.java:329)
02-23 12:26:34.723 18718 18718 E WindowManager:         at android.support.v7.app.AlertDialog$Builder.show(AlertDialog.java:958)
02-23 12:26:34.723 18718 18718 E WindowManager:         at org.thoughtcrime.securesms.preferences.AdvancedPreferenceFragment.handleEvent(AdvancedPreferenceFragment.java:375)
02-23 12:26:34.723 18718 18718 E WindowManager:         at com.b44t.messenger.DcEventCenter.lambda$sendToObservers$0$DcEventCenter(DcEventCenter.java:71)
02-23 12:26:34.723 18718 18718 E WindowManager:         at com.b44t.messenger.DcEventCenter$$Lambda$0.run(Unknown Source)
02-23 12:26:34.723 18718 18718 E WindowManager:         at android.os.Handler.handleCallback(Handler.java:751)
02-23 12:26:34.723 18718 18718 E WindowManager:         at android.os.Handler.dispatchMessage(Handler.java:95)
02-23 12:26:34.723 18718 18718 E WindowManager:         at android.os.Looper.loop(Looper.java:154)
02-23 12:26:34.723 18718 18718 E WindowManager:         at android.app.ActivityThread.main(ActivityThread.java:6186)
02-23 12:26:34.723 18718 18718 E WindowManager:         at java.lang.reflect.Method.invoke(Native Method)
02-23 12:26:34.723 18718 18718 E WindowManager:         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
02-23 12:26:34.723 18718 18718 E WindowManager:         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)

02-23 12:26:38.608  2384  4706 I ActivityManager: START u0 {cmp=com.b44t.messenger/org.thoughtcrime.securesms.ApplicationPreferencesActivity} from uid 10074 on display 0

02-23 12:26:49.289 18718 18736 I DeltaChat: Import/export process started.
02-23 12:26:49.292 18718 18736 I DeltaChat: Exporting key /storage/emulated/0/Download/public-key-default.asc
02-23 12:26:49.292 18718 18736 W DeltaChat: Cannot delete "/storage/emulated/0/Download/public-key-default.asc".
02-23 12:26:49.293 18718 18736 W DeltaChat: Cannot open "/storage/emulated/0/Download/public-key-default.asc" for writing.
02-23 12:26:49.294 18718 18736 E DeltaChat: Cannot write key to /storage/emulated/0/Download/public-key-default.asc
02-23 12:26:49.294 18718 18736 I DeltaChat: Exporting key /storage/emulated/0/Download/private-key-default.asc
02-23 12:26:49.295 18718 18736 W DeltaChat: Cannot delete "/storage/emulated/0/Download/private-key-default.asc".
02-23 12:26:49.299 18718 18736 W DeltaChat: Cannot open "/storage/emulated/0/Download/private-key-default.asc" for writing.
02-23 12:26:49.300 18718 18736 E DeltaChat: Cannot write key to /storage/emulated/0/Download/private-key-default.asc
02-23 12:26:49.311 18718 18736 I DeltaChat: Import/export completed.

02-23 12:31:50.108  2384  2398 I ActivityManager: START u0 {act=android.settings.APP_OPS_DETAILS_SETTINGS dat=package:com.b44t.messenger cmp=com.android.settings/.applications.AppOpsDetails} from uid 1000 on display 0
02-23 12:31:50.110  2384  2398 W ActivityManager: startActivity called from non-Activity context; forcing Intent.FLAG_ACTIVITY_NEW_TASK for: Intent { act=android.settings.APP_OPS_DETAILS_SETTINGS dat=package:com.b44t.messenger flg=0x800000 cmp=com.android.settings/.applications.AppOpsDetails }
02-23 12:31:50.137  2384  2398 E ActivityManager: applyOptionsLocked: Unknown animationType=0
02-23 12:31:50.138  2384  2398 I WindowManager: Failed to capture screenshot of Token{681bacc ActivityRecord{98b9cff u0 com.b44t.messenger/org.thoughtcrime.securesms.ApplicationPreferencesActivity t12803}} appWin=Window{b870a1b u0 com.b44t.messenger/org.thoughtcrime.securesms.ApplicationPreferencesActivity} drawState=4
```

Does DC need to activate the "write to external storage" access in some way?

**Comment by phmarek** [comment]
![](file:///tmp/Screenshot_20190223-123353.png)

**Comment by phmarek** [comment]
As an update: I could now export the key successfully - I guess that one the first try delta chat had just asked for the permission but didn't get restarted right away (so that the process has the required unix group); in the meantime I rebooted the phone, perhaps that's why it works now.

Still, the basic bug remains - a "success" message even if the export fails.

**Comment by r10s** [comment]
should be fixed by https://github.com/deltachat/deltachat-core/commit/df4e4a4fb287fe425cb9318284ea7017c0b35d2b
